Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libAlc/AlcArray.c File Reference
AlcArray.c File Reference
AlcArray
Provides functions for the allocation of 1, 2 and 3D arrays of types char, short, int, float and double. Extension to other types (including user defined types) should be straight formward through templates defined in AlcTemplates.h.
Functions
AlcErrno AlcBit1Calloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional zero'd bit array.
AlcErrno AlcPtr1Calloc (void ***dest, size_t mElem)
Allocates a 1 dimensional zero'd array of pointers to void.
AlcErrno AlcChar1Calloc (char **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of chars.
AlcErrno AlcUnchar1Calloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of unsigned chars.
AlcErrno AlcShort1Calloc (short **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of shorts.
AlcErrno AlcInt1Calloc (int **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of ints.
AlcErrno AlcFloat1Calloc (float **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of floats.
AlcErrno AlcDouble1Calloc (double **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of doubles.
AlcErrno AlcBit1Malloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd bit array.
AlcErrno AlcPtr1Malloc (void ***dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of pointers to void.
AlcErrno AlcChar1Malloc (char **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of chars.
AlcErrno AlcUnchar1Malloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of unsigned chars.
AlcErrno AlcShort1Malloc (short **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of shorts.
AlcErrno AlcInt1Malloc (int **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of ints.
AlcErrno AlcFloat1Malloc (float **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of floats.
AlcErrno AlcDouble1Malloc (double **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of doubles.
AlcErrno AlcBit2Calloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd bit array.
AlcErrno AlcPtr2Calloc (void ****dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of pointers to void.
AlcErrno AlcChar2Calloc (char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of chars.
AlcErrno AlcUnchar2Calloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of unsigned chars.
AlcErrno AlcShort2Calloc (short ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of shorts.
AlcErrno AlcInt2Calloc (int ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of ints.
AlcErrno AlcFloat2Calloc (float ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of floats.
AlcErrno AlcDouble2Calloc (double ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of doubles.
AlcErrno AlcBit2Malloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd bit array.
AlcErrno AlcPtr2Malloc (void ****dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of pointers to void.
AlcErrno AlcChar2Malloc (char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of chars.
AlcErrno AlcUnchar2Malloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of unsigned chars.
AlcErrno AlcShort2Malloc (short ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of shorts.
AlcErrno AlcInt2Malloc (int ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of ints.
AlcErrno AlcFloat2Malloc (float ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of floats.
AlcErrno AlcDouble2Malloc (double ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of doubles.
AlcErrno AlcSymChar2Calloc (char ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymUnchar2Calloc (unsigned char ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of unsigned chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymShort2Calloc (short ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of shorts in which only the lower triangle of elements are stored.
AlcErrno AlcSymInt2Calloc (int ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of ints in which only the lower triangle of elements are stored.
AlcErrno AlcSymFloat2Calloc (float ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of floats in which only the lower triangle of elements are stored.
AlcErrno AlcSymDouble2Calloc (double ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of doubles in which only the lower triangle of elements are stored.
AlcErrno AlcSymChar2Malloc (char ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymUnchar2Malloc (unsigned char ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of unsigned chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymShort2Malloc (short ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of shorts in which only the lower triangle of elements are stored.
AlcErrno AlcSymInt2Malloc (int ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of ints in which only the lower triangle of elements are stored.
AlcErrno AlcSymFloat2Malloc (float ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of floats in which only the lower triangle of elements are stored.
AlcErrno AlcSymDouble2Malloc (double ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of doubles in which only the lower triangle of elements are stored.
AlcErrno Alc2Free (void **dat)
Free's a 2 dimensional array allocated by one of the 2 dimensional array allocation functions.
AlcErrno AlcBit2Free (unsigned char **dat)
AlcErrno AlcChar2Free (char **dat)
AlcErrno AlcUnchar2Free (unsigned char **dat)
AlcErrno AlcShort2Free (short **dat)
AlcErrno AlcInt2Free (int **dat)
AlcErrno AlcFloat2Free (float **dat)
AlcErrno AlcDouble2Free (double **dat)
AlcErrno AlcBit3Calloc (unsigned char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional zero'd bit array.
AlcErrno AlcPtr3Calloc (void *****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of pointers to void.
AlcErrno AlcChar3Calloc (char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcUnchar3Calloc (unsigned char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of unsigned chars.
AlcErrno AlcShort3Calloc (short ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcInt3Calloc (int ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcFloat3Calloc (float ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcDouble3Calloc (double ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional zero'd array of doubles.
AlcErrno AlcBit3Malloc (unsigned char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd bit array.
AlcErrno AlcPtr3Malloc (void *****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of pointers to void.
AlcErrno AlcChar3Malloc (char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of chars.
AlcErrno AlcUnchar3Malloc (unsigned char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of unsigned chars.
AlcErrno AlcShort3Malloc (short ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of shorts.
AlcErrno AlcInt3Malloc (int ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of ints.
AlcErrno AlcFloat3Malloc (float ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of floats.
AlcErrno AlcDouble3Malloc (double ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of doubles.
AlcErrno Alc3Free (void ***dest)
Free's any 3 dimensional array allocated by one of the 3 dimensional array allocation functions.
AlcErrno AlcBit3Free (unsigned char ***dest)
AlcErrno AlcChar3Free (char ***dest)
AlcErrno AlcUnchar3Free (unsigned char ***dest)
AlcErrno AlcShort3Free (short ***dest)
AlcErrno AlcInt3Free (int ***dest)
AlcErrno AlcFloat3Free (float ***dest)
AlcErrno AlcDouble3Free (double ***dest)
AlcErrno AlcDouble1ReadAsci (FILE *fP, double **dstA, size_t *dstNElem)
Reads a 1D double array from the given numeric ASCI file. Each value should be on a seperate line.
AlcErrno AlcDouble2ReadAsci (FILE *fP, double ***dstA, size_t *dstMElem, size_t *dstNElem)
Reads a 2D double array from the given numeric ASCI file. Fields in the file must be white space saperated and records must be on separate lines. The number of fields per record must be the same for all records.
AlcErrno AlcDouble1WriteAsci (FILE *fP, double *ar, size_t nElem)
Writes a 1D double array in numeric ASCI format to the given file file. Elements are on separate lines.
AlcErrno AlcDouble2WriteAsci (FILE *fP, double **ar, size_t mElem, size_t nElem)
Writes a 2D double array in numeric ASCI format to the given file file. Fields in the file are white space seperated and records are on separate lines.
Detailed Description
Provides functions for the allocation of 1, 2 and 3D arrays of types char, short, int, float and double. Extension to other types (including user defined types) should be straight formward through templates defined in AlcTemplates.h.
Author
Bill Hill
Date
April 2001
Version
Id
fce45eaa48f4cdf2cbd5c154e7506fd30b055f4e
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
AlcErrno AlcBit2Free (unsigned char ** dat)
References AlcUnchar2Free().
Referenced by WlzFromBArray1D().
AlcErrno AlcChar2Free (char ** dat)
References ALC_TEMPLATE_F2D.
Referenced by AlcUnchar2Free().
AlcErrno AlcUnchar2Free (unsigned char ** dat)
References AlcChar2Free().
Referenced by AlcBit2Free().
AlcErrno AlcShort2Free (short ** dat)
References ALC_TEMPLATE_F2D.
AlcErrno AlcInt2Free (int ** dat)
References ALC_TEMPLATE_F2D.
Referenced by WlzSampleObj(), and WlzSampleObjPoint2D().
AlcErrno AlcFloat2Free (float ** dat)
References ALC_TEMPLATE_F2D.
AlcErrno AlcDouble2Free (double ** dat)
References ALC_TEMPLATE_F2D.
Referenced by AlgMatrixRectFree(), AlgMatrixSymFree(), AlgMixtureMLG(), WlzAffineTransformLSqReg2D(), WlzAffineTransformLSqReg3D(), WlzAffineTransformLSqRegWlz2D(), WlzFreeAffineTransform(), WlzInit3DViewStructAffineTransform(), WlzRegCCorObjs(), WlzSampleObj(), and WlzSampleObjPoint2D().
AlcErrno AlcDouble3Calloc (double **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional zero'd array of doubles.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_C3D.
Referenced by WlzRegICPVerticesWSD2D().
AlcErrno AlcBit3Malloc (unsigned char **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd bit array.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References AlcUnchar3Malloc().
Referenced by WlzRsvFilterBuffer(), and WlzToArray3D().
AlcErrno AlcBit3Free (unsigned char *** dest)
References AlcUnchar3Free().
AlcErrno AlcChar3Free (char *** dest)
References ALC_TEMPLATE_F3D.
Referenced by AlcUnchar3Free().
AlcErrno AlcUnchar3Free (unsigned char *** dest)
References AlcChar3Free().
Referenced by AlcBit3Free(), WlzEffReadObjDen(), WlzEffWriteObjDen(), WlzEffWriteObjIcs(), WlzEffWriteObjPic(), WlzEffWriteObjPvl(), WlzEffWriteObjVff(), and WlzEffWriteObjVtk().
AlcErrno AlcShort3Free (short *** dest)
References ALC_TEMPLATE_F3D.
AlcErrno AlcInt3Free (int *** dest)
References ALC_TEMPLATE_F3D.
AlcErrno AlcFloat3Free (float *** dest)
References ALC_TEMPLATE_F3D.
AlcErrno AlcDouble3Free (double *** dest)
References ALC_TEMPLATE_F3D.