Woolz Image Processing: AlcArray
AlcArray
Files
file AlcArray.c
Provides functions for the allocation of 1, 2 and 3D arrays of types char, short, int, float and double. Extension to other types (including user defined types) should be straight formward through templates defined in AlcTemplates.h.
Macros
#define ALC_TEMPLATE_C1D(D, T, M, F)
A template for functions which allocate 1 dimensional zero'd arrays of any type.
#define ALC_TEMPLATE_M1D(D, T, M, F)
A template for functions which allocate 1 dimensional non-zero'd arrays of any type.
#define ALC_TEMPLATE_C2D(D, T, M, N, F)
A template for functions which allocate 2 dimensional zero'd arrays of any type.
#define ALC_TEMPLATE_M2D(D, T, M, N, F)
A template for functions which allocate 2 dimensional non-zero'd arrays of any type.
#define ALC_TEMPLATE_SYM_C2D(D, T, N, F)
A template for functions which allocate 2 dimensional zero'd symetric arrays of any type. Obviously symetric arrays are square, but in this representation only the lower trinagle is stored.
#define ALC_TEMPLATE_SYM_M2D(D, T, N, F)
A template for functions which allocate 2 dimensional zero'd symetric arrays of any type. Obviously symetric arrays are square, but in this representation only the lower trinagle is stored.
#define ALC_TEMPLATE_F2D(D, F)
A template for functions which free 2 dimensional arrays of any type, actualy no type information is used in freeing the array.
#define ALC_TEMPLATE_C3D(D, T, M, N, O, F)
A template for functions which allocate 3 dimensional zero'd arrays of any type.
#define ALC_TEMPLATE_M3D(D, T, M, N, O, F)
A template for functions which allocate 3 dimensional non-zero'd arrays of any type.
#define ALC_TEMPLATE_F3D(D, F)
A template for functions which free 3 dimensional arrays of any type, actualy no type information is used in freeing the array.
Functions
AlcErrno AlcBit1Calloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional zero'd bit array.
AlcErrno AlcPtr1Calloc (void ***dest, size_t mElem)
Allocates a 1 dimensional zero'd array of pointers to void.
AlcErrno AlcChar1Calloc (char **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of chars.
AlcErrno AlcUnchar1Calloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of unsigned chars.
AlcErrno AlcShort1Calloc (short **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of shorts.
AlcErrno AlcInt1Calloc (int **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of ints.
AlcErrno AlcFloat1Calloc (float **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of floats.
AlcErrno AlcDouble1Calloc (double **dest, size_t mElem)
Allocates a 1 dimensional zero'd array of doubles.
AlcErrno AlcBit1Malloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd bit array.
AlcErrno AlcPtr1Malloc (void ***dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of pointers to void.
AlcErrno AlcChar1Malloc (char **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of chars.
AlcErrno AlcUnchar1Malloc (unsigned char **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of unsigned chars.
AlcErrno AlcShort1Malloc (short **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of shorts.
AlcErrno AlcInt1Malloc (int **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of ints.
AlcErrno AlcFloat1Malloc (float **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of floats.
AlcErrno AlcDouble1Malloc (double **dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of doubles.
AlcErrno AlcBit2Calloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd bit array.
AlcErrno AlcPtr2Calloc (void ****dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of pointers to void.
AlcErrno AlcChar2Calloc (char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of chars.
AlcErrno AlcUnchar2Calloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of unsigned chars.
AlcErrno AlcShort2Calloc (short ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of shorts.
AlcErrno AlcInt2Calloc (int ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of ints.
AlcErrno AlcFloat2Calloc (float ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of floats.
AlcErrno AlcDouble2Calloc (double ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of doubles.
AlcErrno AlcBit2Malloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd bit array.
AlcErrno AlcPtr2Malloc (void ****dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of pointers to void.
AlcErrno AlcChar2Malloc (char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of chars.
AlcErrno AlcUnchar2Malloc (unsigned char ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of unsigned chars.
AlcErrno AlcShort2Malloc (short ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of shorts.
AlcErrno AlcInt2Malloc (int ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of ints.
AlcErrno AlcFloat2Malloc (float ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of floats.
AlcErrno AlcDouble2Malloc (double ***dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of doubles.
AlcErrno AlcSymChar2Calloc (char ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymUnchar2Calloc (unsigned char ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of unsigned chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymShort2Calloc (short ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of shorts in which only the lower triangle of elements are stored.
AlcErrno AlcSymInt2Calloc (int ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of ints in which only the lower triangle of elements are stored.
AlcErrno AlcSymFloat2Calloc (float ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of floats in which only the lower triangle of elements are stored.
AlcErrno AlcSymDouble2Calloc (double ***dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of doubles in which only the lower triangle of elements are stored.
AlcErrno AlcSymChar2Malloc (char ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymUnchar2Malloc (unsigned char ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of unsigned chars in which only the lower triangle of elements are stored.
AlcErrno AlcSymShort2Malloc (short ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of shorts in which only the lower triangle of elements are stored.
AlcErrno AlcSymInt2Malloc (int ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of ints in which only the lower triangle of elements are stored.
AlcErrno AlcSymFloat2Malloc (float ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of floats in which only the lower triangle of elements are stored.
AlcErrno AlcSymDouble2Malloc (double ***dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of doubles in which only the lower triangle of elements are stored.
AlcErrno Alc2Free (void **dat)
Free's a 2 dimensional array allocated by one of the 2 dimensional array allocation functions.
AlcErrno AlcBit3Calloc (unsigned char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional zero'd bit array.
AlcErrno AlcPtr3Calloc (void *****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of pointers to void.
AlcErrno AlcChar3Calloc (char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcUnchar3Calloc (unsigned char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of unsigned chars.
AlcErrno AlcShort3Calloc (short ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcInt3Calloc (int ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcFloat3Calloc (float ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
AlcErrno AlcPtr3Malloc (void *****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of pointers to void.
AlcErrno AlcChar3Malloc (char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of chars.
AlcErrno AlcUnchar3Malloc (unsigned char ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of unsigned chars.
AlcErrno AlcShort3Malloc (short ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of shorts.
AlcErrno AlcInt3Malloc (int ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of ints.
AlcErrno AlcFloat3Malloc (float ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of floats.
AlcErrno AlcDouble3Malloc (double ****dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of doubles.
AlcErrno Alc3Free (void ***dest)
Free's any 3 dimensional array allocated by one of the 3 dimensional array allocation functions.
AlcErrno AlcDouble1ReadAsci (FILE *fP, double **dstA, size_t *dstNElem)
Reads a 1D double array from the given numeric ASCI file. Each value should be on a seperate line.
AlcErrno AlcDouble2ReadAsci (FILE *fP, double ***dstA, size_t *dstMElem, size_t *dstNElem)
Reads a 2D double array from the given numeric ASCI file. Fields in the file must be white space saperated and records must be on separate lines. The number of fields per record must be the same for all records.
AlcErrno AlcDouble1WriteAsci (FILE *fP, double *ar, size_t nElem)
Writes a 1D double array in numeric ASCI format to the given file file. Elements are on separate lines.
AlcErrno AlcDouble2WriteAsci (FILE *fP, double **ar, size_t mElem, size_t nElem)
Writes a 2D double array in numeric ASCI format to the given file file. Fields in the file are white space seperated and records are on separate lines.
Detailed Description
Macro Definition Documentation
#define ALC_TEMPLATE_C1D (D, T, M, F)
Value:
AlcErrno        alcErrno = ALC_ER_NONE; \
  \
  if((D) == NULL) \
    alcErrno = ALC_ER_NULLPTR; \
  else if((M) < 1) \
    alcErrno = ALC_ER_NUMELEM; \
  else if((*(D) = (T*)AlcCalloc((M), sizeof(T))) == NULL) \
    alcErrno = ALC_ER_ALLOC; \
  if(alcErrno != ALC_ER_NONE) \
  { \
    if(D) \
      *(D) = NULL; \
  } \
  return(alcErrno);
A template for functions which allocate 1 dimensional zero'd arrays of any type.
Parameters
D Destination pointer, of type T *.
T Type, eg char, short, int, ....
M Number of elements in array.
F String with name of function.
Referenced by AlcChar1Calloc(), AlcDouble1Calloc(), AlcFloat1Calloc(), AlcInt1Calloc(), and AlcShort1Calloc().
#define ALC_TEMPLATE_M1D (D, T, M, F)
Value:
AlcErrno        alcErrno = ALC_ER_NONE; \
  \
  if((D) == NULL) \
    alcErrno = ALC_ER_NULLPTR; \
  else if((M) < 1) \
    alcErrno = ALC_ER_NUMELEM; \
  else if((*(D) = (T*)AlcMalloc((M) * sizeof(T))) == NULL) \
    alcErrno = ALC_ER_ALLOC; \
  if(alcErrno != ALC_ER_NONE) \
  { \
    if(D) \
      *(D) = NULL; \
  } \
  return(alcErrno);
A template for functions which allocate 1 dimensional non-zero'd arrays of any type.
Parameters
D Destination pointer, of type T *.
T Type, eg char, short, int, ....
M Number of elements in array.
F String with name of function.
Referenced by AlcChar1Malloc(), AlcDouble1Malloc(), AlcFloat1Malloc(), AlcInt1Malloc(), and AlcShort1Malloc().
#define ALC_TEMPLATE_C2D (D, T, M, N, F)
A template for functions which allocate 2 dimensional zero'd arrays of any type.
Parameters
D Destination pointer, of type T **.
T Type, eg char, short, int, ....
M Number of 1D arrays.
N Number of elements in each 1D array.
F String with name of function.
Referenced by AlcChar2Calloc(), AlcDouble2Calloc(), AlcFloat2Calloc(), AlcInt2Calloc(), and AlcShort2Calloc().
#define ALC_TEMPLATE_M2D (D, T, M, N, F)
A template for functions which allocate 2 dimensional non-zero'd arrays of any type.
Parameters
D Destination pointer, of type T **.
T Type, eg char, short, int, ....
M Number of 1D arrays.
N Number of elements in each 1D array.
F String with name of function.
Referenced by AlcChar2Malloc(), AlcDouble2Malloc(), AlcFloat2Malloc(), AlcInt2Malloc(), and AlcShort2Malloc().
#define ALC_TEMPLATE_SYM_C2D (D, T, N, F)
A template for functions which allocate 2 dimensional zero'd symetric arrays of any type. Obviously symetric arrays are square, but in this representation only the lower trinagle is stored.
Parameters
D Destination pointer, of type T **.
T Type, eg char, short, int, ....
N Number of rows or columns.
F String with name of function.
Referenced by AlcSymChar2Calloc(), AlcSymDouble2Calloc(), AlcSymFloat2Calloc(), AlcSymInt2Calloc(), and AlcSymShort2Calloc().
#define ALC_TEMPLATE_SYM_M2D (D, T, N, F)
A template for functions which allocate 2 dimensional zero'd symetric arrays of any type. Obviously symetric arrays are square, but in this representation only the lower trinagle is stored.
Parameters
D Destination pointer, of type T **.
T Type, eg char, short, int, ....
N Number of rows or columns.
F String with name of function.
Referenced by AlcSymChar2Malloc(), AlcSymDouble2Malloc(), AlcSymFloat2Malloc(), AlcSymInt2Malloc(), and AlcSymShort2Malloc().
#define ALC_TEMPLATE_F2D (D, F)
Value:
AlcErrno        alcErrno = ALC_ER_NONE; \
  \
  if((D == NULL) || (*(D) == NULL)) \
  { \
    alcErrno = ALC_ER_NULLPTR; \
  } \
  else \
  { \
    AlcFree(*(D)); \
    AlcFree(D); \
  } \
  return(alcErrno);
A template for functions which free 2 dimensional arrays of any type, actualy no type information is used in freeing the array.
Parameters
D Pointer for array to be free'd.
F String with name of function.
Referenced by Alc2Free(), AlcChar2Free(), AlcDouble2Free(), AlcFloat2Free(), AlcInt2Free(), and AlcShort2Free().
#define ALC_TEMPLATE_C3D (D, T, M, N, O, F)
A template for functions which allocate 3 dimensional zero'd arrays of any type.
Parameters
D Destination pointer, of type T **.
T Type, eg char, short, int, ....
M Number of 2D arrays.
N Number of 1D arrays.
O Number of elements in each 1D array.
F String with name of function.
Referenced by AlcChar3Calloc(), AlcDouble3Calloc(), AlcFloat3Calloc(), AlcInt3Calloc(), and AlcShort3Calloc().
#define ALC_TEMPLATE_M3D (D, T, M, N, O, F)
A template for functions which allocate 3 dimensional non-zero'd arrays of any type.
Parameters
D Destination pointer, of type T **.
T Type, eg char, short, int, ....
M Number of 2D arrays.
N Number of 1D arrays.
O Number of elements in each 1D array.
F String with name of function.
Referenced by AlcChar3Malloc(), AlcDouble3Malloc(), AlcFloat3Malloc(), AlcInt3Malloc(), and AlcShort3Malloc().
#define ALC_TEMPLATE_F3D (D, F)
Value:
AlcErrno        alcErrno = ALC_ER_NONE; \
  \
  if((D == NULL) || (*(D) == NULL) || (**(D) == NULL)) \
  { \
    alcErrno = ALC_ER_NULLPTR; \
  } \
  else \
  { \
    AlcFree(**(D)); \
    AlcFree(*(D)); \
    AlcFree(D); \
  } \
  return(alcErrno);
A template for functions which free 3 dimensional arrays of any type, actualy no type information is used in freeing the array.
Parameters
D Pointer for array to be free'd.
F String with name of function.
Referenced by Alc3Free(), AlcChar3Free(), AlcDouble3Free(), AlcFloat3Free(), AlcInt3Free(), and AlcShort3Free().
Function Documentation
AlcErrno AlcBit1Calloc (unsigned char ** dest, size_t mElem)
Allocates a 1 dimensional zero'd bit array.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References AlcUnchar1Calloc().
Referenced by WlzCMeshToDomObjValues(), WlzCMeshTransformManyObjAsIdx(), and WlzContourFromPoints().
AlcErrno AlcPtr1Calloc (void *** dest, size_t mElem)
Allocates a 1 dimensional zero'd array of pointers to void.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_ER_ALLOC, ALC_ER_NONE, ALC_ER_NULLPTR, ALC_ER_NUMELEM, and AlcCalloc().
AlcErrno AlcChar1Calloc (char ** dest, size_t mElem)
Allocates a 1 dimensional zero'd array of chars.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_C1D.
Referenced by AlcUnchar1Calloc().
AlcErrno AlcUnchar1Calloc (unsigned char ** dest, size_t mElem)
Allocates a 1 dimensional zero'd array of unsigned chars.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References AlcChar1Calloc().
Referenced by AlcBit1Calloc().
AlcErrno AlcShort1Calloc (short ** dest, size_t mElem)
Allocates a 1 dimensional zero'd array of shorts.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_C1D.
AlcErrno AlcInt1Calloc (int ** dest, size_t mElem)
Allocates a 1 dimensional zero'd array of ints.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_C1D.
AlcErrno AlcFloat1Calloc (float ** dest, size_t mElem)
Allocates a 1 dimensional zero'd array of floats.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_C1D.
AlcErrno AlcDouble1Calloc (double ** dest, size_t mElem)
Allocates a 1 dimensional zero'd array of doubles.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_C1D.
AlcErrno AlcBit1Malloc (unsigned char ** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd bit array.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References AlcUnchar1Malloc().
AlcErrno AlcPtr1Malloc (void *** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of pointers to void.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_ER_ALLOC, ALC_ER_NONE, ALC_ER_NULLPTR, ALC_ER_NUMELEM, and AlcMalloc().
AlcErrno AlcChar1Malloc (char ** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of chars.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_M1D.
Referenced by AlcUnchar1Malloc().
AlcErrno AlcUnchar1Malloc (unsigned char ** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of unsigned chars.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References AlcChar1Malloc().
Referenced by AlcBit1Malloc().
AlcErrno AlcShort1Malloc (short ** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of shorts.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_M1D.
AlcErrno AlcInt1Malloc (int ** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of ints.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_M1D.
AlcErrno AlcFloat1Malloc (float ** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of floats.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_M1D.
AlcErrno AlcDouble1Malloc (double ** dest, size_t mElem)
Allocates a 1 dimensional non-zero'd array of doubles.
Returns
Error code.
Note
Should be free'd using AlcFree().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of elements in array.
References ALC_TEMPLATE_M1D.
Referenced by Wlz3DViewStructSetupTransformLuts(), WlzAffineTransformLSqRegWlz2D(), and WlzContourFromPoints().
AlcErrno AlcBit2Calloc (unsigned char *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd bit array.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References AlcUnchar2Calloc().
Referenced by WlzAffineTransformGMShell(), WlzContourFromPoints(), WlzContourGrdObj2D(), WlzContourRBFBndObj3D(), WlzFromBArray1D(), and WlzRankFilter().
AlcErrno AlcPtr2Calloc (void **** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of pointers to void.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_ER_ALLOC, ALC_ER_NONE, ALC_ER_NULLPTR, ALC_ER_NUMELEM, AlcCalloc(), AlcFree(), and AlcMalloc().
AlcErrno AlcChar2Calloc (char *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of chars.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_C2D.
Referenced by AlcUnchar2Calloc().
AlcErrno AlcUnchar2Calloc (unsigned char *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of unsigned chars.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References AlcChar2Calloc().
Referenced by AlcBit2Calloc(), WlzCMeshCompSurfMap(), WlzContourGrdObj2D(), and WlzProjectObjToPlane().
AlcErrno AlcShort2Calloc (short *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of shorts.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_C2D.
AlcErrno AlcInt2Calloc (int *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of ints.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_C2D.
Referenced by WlzProjectObjToPlane().
AlcErrno AlcFloat2Calloc (float *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of floats.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_C2D.
AlcErrno AlcDouble2Calloc (double *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional zero'd array of doubles.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_C2D.
Referenced by AlgMatrixRectNew(), WlzContourGrdObj2D(), and WlzMakeAffineTransform().
AlcErrno AlcBit2Malloc (unsigned char *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd bit array.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References AlcUnchar2Malloc().
Referenced by WlzRsvFilterBuffer(), and WlzToArray2D().
AlcErrno AlcPtr2Malloc (void **** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of pointers to void.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_ER_ALLOC, ALC_ER_NONE, ALC_ER_NULLPTR, ALC_ER_NUMELEM, AlcFree(), and AlcMalloc().
AlcErrno AlcChar2Malloc (char *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of chars.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_M2D.
Referenced by AlcUnchar2Malloc().
AlcErrno AlcUnchar2Malloc (unsigned char *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of unsigned chars.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References AlcChar2Malloc().
Referenced by AlcBit2Malloc(), WlzEffReadObjBmpData2D(), WlzEffReadObjPnmData2D(), and WlzRankFilter().
AlcErrno AlcShort2Malloc (short *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of shorts.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_M2D.
Referenced by WlzRankFilter().
AlcErrno AlcInt2Malloc (int *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of ints.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_M2D.
Referenced by WlzEffReadObjGif(), WlzRankFilter(), WlzSampleObj(), and WlzSampleObjPoint2D().
AlcErrno AlcFloat2Malloc (float *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of floats.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_M2D.
Referenced by WlzRankFilter().
AlcErrno AlcDouble2Malloc (double *** dest, size_t mElem, size_t nElem)
Allocates a 2 dimensional non-zero'd array of doubles.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 1D arrays.
nElem Number of elements in each 1D array.
References ALC_TEMPLATE_M2D.
Referenced by AlgMixtureMLG(), WlzAffineTransformLSqReg2D(), WlzAffineTransformLSqReg3D(), WlzAffineTransformLSqRegWlz2D(), WlzAutoCor(), WlzContourFromPoints(), WlzContourGrdObj2D(), WlzInit3DViewStructAffineTransform(), WlzRankFilter(), WlzRsvFilterBuffer(), WlzSampleObj(), and WlzSampleObjPoint2D().
AlcErrno AlcSymChar2Calloc (char *** dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of chars in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_C2D.
Referenced by AlcSymUnchar2Calloc().
AlcErrno AlcSymUnchar2Calloc (unsigned char *** dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of unsigned chars in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References AlcSymChar2Calloc().
AlcErrno AlcSymShort2Calloc (short *** dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of shorts in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_C2D.
AlcErrno AlcSymInt2Calloc (int *** dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of ints in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_C2D.
AlcErrno AlcSymFloat2Calloc (float *** dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of floats in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_C2D.
AlcErrno AlcSymDouble2Calloc (double *** dest, size_t nElem)
Allocates a 2 dimensional zero'd symetric array of doubles in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_C2D.
AlcErrno AlcSymChar2Malloc (char *** dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of chars in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_M2D.
Referenced by AlcSymUnchar2Malloc().
AlcErrno AlcSymUnchar2Malloc (unsigned char *** dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of unsigned chars in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References AlcSymChar2Malloc().
AlcErrno AlcSymShort2Malloc (short *** dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of shorts in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_M2D.
AlcErrno AlcSymInt2Malloc (int *** dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of ints in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_M2D.
AlcErrno AlcSymFloat2Malloc (float *** dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of floats in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_M2D.
AlcErrno AlcSymDouble2Malloc (double *** dest, size_t nElem)
Allocates a 2 dimensional non-zero'd symetric array of doubles in which only the lower triangle of elements are stored.
Returns
Error code.
Note
Should be free'd using Alc2Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
nElem Number of row or column elements in the symetric array.
References ALC_TEMPLATE_SYM_M2D.
AlcErrno Alc2Free (void ** dat)
Free's a 2 dimensional array allocated by one of the 2 dimensional array allocation functions.
Returns
Error code.
Parameters
dat Ptr with array to be free'd.
References ALC_TEMPLATE_F2D.
Referenced by WlzAffineTransformGMShell(), WlzAutoCor(), WlzCMeshCompSurfMap(), WlzContourFromPoints(), WlzContourGrdObj2D(), WlzContourRBFBndObj3D(), WlzEffReadObjGif(), WlzEffWriteObjAnl(), WlzEffWriteObjNifti(), WlzEffWriteObjStack(), WlzFourierTransformObj(), WlzImageBlendObjToBufRGBA(), WlzProjectObjToPlane(), WlzRankFilter(), and WlzRsvFilterBuffer().
AlcErrno AlcBit3Calloc (unsigned char **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional zero'd bit array.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References AlcUnchar3Calloc().
Referenced by WlzRankFilter(), and WlzRasterLineSetItv2D().
AlcErrno AlcPtr3Calloc (void ***** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of pointers to void.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_ER_ALLOC, ALC_ER_NONE, ALC_ER_NULLPTR, ALC_ER_NUMELEM, AlcCalloc(), AlcFree(), and AlcMalloc().
AlcErrno AlcChar3Calloc (char **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_C3D.
Referenced by AlcUnchar3Calloc().
AlcErrno AlcUnchar3Calloc (unsigned char **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of unsigned chars.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References AlcChar3Calloc().
Referenced by AlcBit3Calloc().
AlcErrno AlcShort3Calloc (short **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_C3D.
AlcErrno AlcInt3Calloc (int **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_C3D.
AlcErrno AlcFloat3Calloc (float **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional array of chars.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_C3D.
AlcErrno AlcPtr3Malloc (void ***** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of pointers to void.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_ER_ALLOC, ALC_ER_NONE, ALC_ER_NULLPTR, ALC_ER_NUMELEM, AlcFree(), and AlcMalloc().
Referenced by WlzGeoModelGridWSpSet3D().
AlcErrno AlcChar3Malloc (char **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of chars.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_M3D.
Referenced by AlcUnchar3Malloc(), and WlzEffWriteObjAm().
AlcErrno AlcUnchar3Malloc (unsigned char **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of unsigned chars.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References AlcChar3Malloc().
Referenced by AlcBit3Malloc(), WlzEffReadObjDen(), WlzEffReadObjIcs(), WlzEffReadObjIPL(), WlzEffReadObjPic(), WlzEffReadObjSlc(), WlzEffReadObjVff(), WlzEffWriteObjStack(), and WlzRankFilter().
AlcErrno AlcShort3Malloc (short **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of shorts.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_M3D.
Referenced by WlzEffReadObjIcs(), WlzEffReadObjIPL(), WlzEffReadObjPic(), WlzEffReadObjVff(), WlzEffWriteObjAm(), and WlzRankFilter().
AlcErrno AlcInt3Malloc (int **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of ints.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_M3D.
Referenced by WlzEffReadObjIcs(), WlzEffReadObjIPL(), WlzEffReadObjVff(), and WlzRankFilter().
AlcErrno AlcFloat3Malloc (float **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of floats.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_M3D.
Referenced by WlzEffReadObjIPL(), and WlzRankFilter().
AlcErrno AlcDouble3Malloc (double **** dest, size_t mElem, size_t nElem, size_t oElem)
Allocates a 3 dimensional non-zero'd array of doubles.
Returns
Error code.
Note
Should be free'd using Alc3Free().
Array size is limited only by address space.
Parameters
dest Destination for allocated array pointer.
mElem Number of 2D arrays.
nElem Number of 1D arrays.
oElem Number of elements in each 1D array.
References ALC_TEMPLATE_M3D.
Referenced by WlzRankFilter(), and WlzRsvFilterBuffer().
AlcErrno Alc3Free (void *** dest)
Free's any 3 dimensional array allocated by one of the 3 dimensional array allocation functions.
Returns
Error code.
Parameters
dest Ptr with array to be free'd.
References ALC_TEMPLATE_F3D.
Referenced by WlzEffReadObjAm(), WlzEffReadObjIcs(), WlzEffReadObjIPL(), WlzEffReadObjPic(), WlzEffReadObjSlc(), WlzEffReadObjVff(), WlzEffWriteObjAm(), WlzEffWriteObjAnl(), WlzEffWriteObjIPL(), WlzEffWriteObjNifti(), WlzEffWriteObjSlc(), WlzEffWriteObjStack(), WlzFourierTransformObj(), WlzGeoModelGridFree3D(), WlzGeoModelGridWSpSet3D(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzRegICPVerticesWSD2D(), and WlzRsvFilterBuffer().
AlcErrno AlcDouble1ReadAsci (FILE * fP, double ** dstA, size_t * dstNElem)
Reads a 1D double array from the given numeric ASCI file. Each value should be on a seperate line.
Returns
Error code.
Parameters
fP File pointer.
dstA Destination pointer for the new array.
dstNElem Destination pointer for the number of elements in the 1D array.
References ALC_ER_NONE, AlcVecReadDouble1Asci(), AlcVectorFree(), and AlcVectorToArray1D().
AlcErrno AlcDouble2ReadAsci (FILE * fP, double *** dstA, size_t * dstMElem, size_t * dstNElem)
Reads a 2D double array from the given numeric ASCI file. Fields in the file must be white space saperated and records must be on separate lines. The number of fields per record must be the same for all records.
Returns
Error code.
Parameters
fP File pointer.
dstA Destination pointer for the new array.
dstMElem Destination pointer for the number of 1D arrays (number of records).
dstNElem Destination pointer for the number of elements in each 1D array (number of fields per record).
References ALC_ER_NONE, AlcVecReadDouble2Asci(), AlcVectorFree(), and AlcVectorToArray2D().
AlcErrno AlcDouble1WriteAsci (FILE * fP, double * ar, size_t nElem)
Writes a 1D double array in numeric ASCI format to the given file file. Elements are on separate lines.
Returns
Error code.
Parameters
fP File pointer.
ar Given array.
nElem Number of elements in the 1D array.
References ALC_ER_NONE, and ALC_ER_WRITE.
Referenced by WlzBasisFnScalarMOS3DFromCPts(), and WlzCMeshCompSurfMap().
AlcErrno AlcDouble2WriteAsci (FILE * fP, double ** ar, size_t mElem, size_t nElem)
Writes a 2D double array in numeric ASCI format to the given file file. Fields in the file are white space seperated and records are on separate lines.
Returns
Error code.
Parameters
fP File pointer.
ar Given array.
mElem Number of 1D arrays (number of records).
nElem Number of elements in each 1D array (number of fields per record).
References ALC_ER_NONE, and ALC_ER_WRITE.
Referenced by WlzRegICPTreeAndVertices(), and WlzRegICPVerticesWSD2D().