Woolz Image Processing: AlgComplex
AlgComplex
Files
file AlgComplexUtils.c
Provides basic complex number utilities.
Functions
double AlgCModSq (ComplexD z)
Computes the square of the modulus of the given complex value.
double AlgCMod (ComplexD z)
Computes the modulus of the given complex value.
double AlgCArg (ComplexD z)
Computes the argument of the given complex value.
double AlgCRe (ComplexD z)
Returns the real component of the given complex value.
double AlgCIm (ComplexD z)
Returns the imaginary component of the given complex value.
ComplexD AlgCConj (ComplexD z)
Returns the complex conjugate of the given complex value.
ComplexD AlgCAdd (ComplexD z1, ComplexD z2)
Computes the sum of the two given complex values.
ComplexD AlgCSub (ComplexD z1, ComplexD z2)
Subtracts the second complex value from the first.
ComplexD AlgCMult (ComplexD z1, ComplexD z2)
Multiplies the second complex value with the first.
ComplexD AlgCDiv (ComplexD z1, ComplexD z2)
Divides the first complex value by the second.
ComplexD AlgCPow (ComplexD z, double y)
Pomputes the value of the given complex value to the power of the given real value.
Detailed Description
Function Documentation
double AlgCModSq (ComplexD z)
Computes the square of the modulus of the given complex value.
Returns
Square of modulus.
Parameters
z Given complex value.
References _ComplexD::im, and _ComplexD::re.
Referenced by AlgCDiv().
double AlgCMod (ComplexD z)
Computes the modulus of the given complex value.
Returns
Modulus.
Parameters
z Given complex value.
References _ComplexD::im, and _ComplexD::re.
Referenced by AlgCPow().
double AlgCArg (ComplexD z)
Computes the argument of the given complex value.
Returns
Argument.
Parameters
z Given complex value.
References _ComplexD::im, and _ComplexD::re.
Referenced by AlgCPow().
double AlgCRe (ComplexD z)
Returns the real component of the given complex value.
Returns
Real component.
Parameters
z Given complex value.
References _ComplexD::re.
double AlgCIm (ComplexD z)
Returns the imaginary component of the given complex value.
Returns
Imaginary component.
Parameters
z Given complex value.
References _ComplexD::im.
ComplexD AlgCConj (ComplexD z)
Returns the complex conjugate of the given complex value.
Returns
Complex conjugate.
Parameters
z Given complex value.
References _ComplexD::im, and _ComplexD::re.
Referenced by AlgCDiv().
ComplexD AlgCAdd (ComplexD z1, ComplexD z2)
Computes the sum of the two given complex values.
Returns
Sum.
Parameters
z1 First complex value.
z2 Second complex value.
References _ComplexD::im, and _ComplexD::re.
ComplexD AlgCSub (ComplexD z1, ComplexD z2)
Subtracts the second complex value from the first.
Returns
Difference.
Parameters
z1 First complex value.
z2 Second complex value.
References _ComplexD::im, and _ComplexD::re.
ComplexD AlgCMult (ComplexD z1, ComplexD z2)
Multiplies the second complex value with the first.
Returns
Product.
Parameters
z1 First complex value.
z2 Second complex value.
References _ComplexD::im, and _ComplexD::re.
Referenced by AlgCDiv(), WlzBasisFnConf2DFromCPts(), and WlzBasisFnValueConf2D().
ComplexD AlgCDiv (ComplexD z1, ComplexD z2)
Divides the first complex value by the second.
Returns
Ratio.
Parameters
z1 First complex value.
z2 Second complex value.
References AlgCConj(), AlgCModSq(), AlgCMult(), _ComplexD::im, and _ComplexD::re.
ComplexD AlgCPow (ComplexD z, double y)
Pomputes the value of the given complex value to the power of the given real value.
Returns
Power.
Parameters
z Given complex value.
y Given real value.
References AlgCArg(), AlgCMod(), _ComplexD::im, and _ComplexD::re.