Woolz Image Processing: AlcString
AlcString
Files
file AlcString.c
Provides functions for string duplication.
Functions
char * AlcStrDup (const char *srcStr)
Allocates space for and duplicates the given NULL terminated character string.
char * AlcStrCat3 (const char *s0, const char *s1, const char *s2)
Concatonates the three given strings in order into a new allocated string buffer. If all strings are null or zero length then NULL is returned, otherwise if a string is null it is omitted.
unsigned int AlcStrSFHash (const char *str)
A hash function for strings based on Paul Hsieh's SuperFastHash function which is covered by the LGPL 2.1 license amongst others. The returned value will always be zero if the given string is null of has zero length.
Detailed Description
Function Documentation
char* AlcStrDup (const char * srcStr)
Allocates space for and duplicates the given NULL terminated character string.
Returns
Duplicated string or NULL on error.
Parameters
srcStr Given string.
References AlcMalloc().
Referenced by BibFileEscapeRestrictedChar(), BibFileFieldError(), BibFileFieldMake(), BibFileFieldParseFmt(), BibFileRecordError(), BibFileRecordMake(), BibFileStrRead(), BibFileUnEscapeRestrictedChar(), main(), WlzChangeEMAPProperty(), WlzEffBibParseFileRecord(), WlzEffWriteObjAm(), WlzEffWriteObjNrrd(), WlzMakeEMAPProperty(), WlzMakeGreyProperty(), WlzMakeNameProperty(), WlzMakeTextProperty(), and WlzStringCopyReplace().
char* AlcStrCat3 (const char * s0, const char * s1, const char * s2)
Concatonates the three given strings in order into a new allocated string buffer. If all strings are null or zero length then NULL is returned, otherwise if a string is null it is omitted.
Returns
New concatonated string that should be freed using AlcFree() or NULL on error.
Parameters
s0 First string.
s1 Second string.
s2 Third string.
References AlcMalloc().
unsigned int AlcStrSFHash (const char * str)
A hash function for strings based on Paul Hsieh's SuperFastHash function which is covered by the LGPL 2.1 license amongst others. The returned value will always be zero if the given string is null of has zero length.
Returns
Numeric hash value for the given sting.
Parameters
str Given string.