Woolz Image Processing: AlcAlloc
AlcAlloc
Files
file AlcAlloc.c
Provides functions for basic storage allocation. In their most basic form are simple wrappers for the ANSI functions malloc(3), calloc(3), realloc(3) and free(3) but they may be used to encapsulate more complex allocation such as for persistant storage.
Functions
void * AlcCalloc (size_t elCount, size_t elSz)
Allocates space for the given number of elements with each element set to zero. At it's most basic this function is a wrapper for calloc(3).
void * AlcMalloc (size_t byteCount)
Allocates space for the given number of bytes with each each element left an undefined value.
void * AlcRealloc (void *givenData, size_t byteCount)
Re-allocates space for the given number of bytes with the contents of given data being unchanged.
void AlcFree (void *data)
Free's the given storage.
Detailed Description
Function Documentation
void* AlcCalloc (size_t elCount, size_t elSz)
Allocates space for the given number of elements with each element set to zero. At it's most basic this function is a wrapper for calloc(3).
Returns
Allocated storage or NULL on error.
Parameters
elCount Number of elements.
elSz Size of an element.
Referenced by AlcBlockStackNew(), AlcCPQQueueNew(), AlcDLPItemNew(), AlcDLPListNew(), AlcHashItemNew(), AlcHashTableNew(), AlcHeapNew(), AlcKDTTreeNew(), AlcLRUCacheNew(), AlcPtr1Calloc(), AlcPtr2Calloc(), AlcPtr3Calloc(), AlcUFTreeNew(), AlcVectorExtend(), AlcVectorNew(), AlcVectorToArray1D(), AlcVectorToArray2D(), AlgMatrixLLRExpand(), AlgMatrixLLRNew(), AlgMatrixLUInvertRaw(), AlgMatrixReadAscii(), AlgMatrixRectNew(), AlgMatrixSolveLSQR(), AlgMatrixSVBackSub(), AlgMatrixSVDecomp(), AlgMatrixSVSolve(), AlgMatrixSymNew(), BibFileFieldMake(), BibFileFieldRead(), BibFileRecordMake(), BibFileRecordRead(), Wlz3DSectionOcc(), WlzAffineTransformIsTranslate(), WlzAffineTransformLSqReg3D(), WlzBasisFnConf2DFromCPts(), WlzBasisFnGauss2DFromCPts(), WlzBasisFnIMQ2DFromCPts(), WlzBasisFnIMQ3DFromCPts(), WlzBasisFnMQ2DFromCPts(), WlzBasisFnMQ3DFromCPts(), WlzBasisFnPoly2DFromCPts(), WlzBasisFnScalarMOS3DFromCPts(), WlzBasisFnTPS2DFromCPts(), WlzBasisFnTransformBoundList(), WlzCMeshCmpElmFeat2D(), WlzCMeshCmpElmFeat3D(), WlzCMeshCompSurfMap(), WlzCMeshCompSurfMapToDomain(), WlzCMeshElmFuse2D(), WlzCMeshElmMinEdgLnSq3D(), WlzCMeshExpansion(), WlzCMeshExpValues(), WlzCMeshFMarNodes2D(), WlzCMeshFMarNodes3D(), WlzCMeshIndexMaskFromValueRange(), WlzCMeshIntersect2Mesh2D(), WlzCMeshNew2D(), WlzCMeshNew2D5(), WlzCMeshNew3D(), WlzCMeshToDomObjValues(), WlzCMeshTransformManyObjAsIdx(), WlzCMeshTrRegSM3D(), WlzCopyIndexedValues(), WlzDGTensorPDFeature(), WlzDiffDomain(), WlzDomainNearby(), WlzEffReadObjBmpData2D(), WlzEffReadObjGif(), WlzEffReadObjJpeg(), WlzEffReadObjVMesh(), WlzEffWriteObjAm(), WlzEffWriteObjIPL(), WlzEffWriteObjNifti(), WlzFilterNObjValues(), WlzFitPlaneSVD(), WlzGeoModelGridWSpNew3D(), WlzGetPatchTree(), WlzGMModelNew(), WlzGMModelRehashVHT(), WlzGMModelResIdx(), WlzGreyValueMakeWSp(), WlzIDomainFromPItv2D(), WlzInteriorityN(), WlzIterate(), WlzLabel(), WlzLabel3D(), WlzLBTDomain2DFromIDomain(), WlzLBTDomain3DFromPDomain(), WlzLBTDomainToIDomain(), WlzLBTDomainToPDomain(), WlzMake3DViewStruct(), WlzMake3DViewStructCopy(), WlzMakeAffineTransform(), WlzMakeBasisFnTransform(), WlzMakeCircleObject(), WlzMakeCompoundArray(), WlzMakeContour(), WlzMakeConvexHullDomain2(), WlzMakeConvexHullDomain3(), WlzMakeCuboid(), WlzMakeEMAPProperty(), WlzMakeEmptyTransform(), WlzMakeGreyProperty(), WlzMakeHistogramDomain(), WlzMakeIndexedValues(), WlzMakeIntervalDomain(), WlzMakeIntervalValues(), WlzMakeLBTDomain2D(), WlzMakeLBTDomain3D(), WlzMakeLUTDomain(), WlzMakeLUTValues(), WlzMakeNameProperty(), WlzMakePatchTree(), WlzMakePlaneDomain(), WlzMakePoints(), WlzMakePointValues(), WlzMakePolygonDomain(), WlzMakePropertyList(), WlzMakeQuadrilateral(), WlzMakeSimpleProperty(), WlzMakeTextProperty(), WlzMakeTiledValueBuffer(), WlzMakeTiledValues(), WlzMakeValueTb(), WlzMakeVoxelValueTb(), WlzMatchICPCtr(), WlzMatchICPWeightMatches(), WlzMeshTransformNew(), WlzMeshTransformVerify(), WlzMeshTransformVtx(), WlzNewObjectValueTable(), WlzObjToBoundary(), WlzObjToConvexHull(), WlzPDomainFromPItv3D(), WlzProjectObjToPlane(), WlzRasterLineSetItv2D(), WlzReadMeshTransform3D(), WlzRegCCorObjs(), WlzRegConCalcRCC(), WlzRsvFilterMakeFilter(), WlzSampleValuesAndCoords(), WlzSepFilter(), WlzSeqPar(), WlzShadeCorrectBFDF(), WlzShiftValues(), and WlzSplitObj().
void* AlcMalloc (size_t byteCount)
Allocates space for the given number of bytes with each each element left an undefined value.
Returns
Allocated storage or NULL on error.
Parameters
byteCount Number of bytes.
Referenced by AlcCPQItemUnlink(), AlcFreeStackPush(), AlcHeapTop(), AlcPtr1Malloc(), AlcPtr2Calloc(), AlcPtr2Malloc(), AlcPtr3Calloc(), AlcPtr3Malloc(), AlcStrCat3(), AlcStrDup(), AlcUFTreeNew(), AlcVecReadDouble1Asci(), AlcVecReadDouble2Asci(), AlcVectorToArray2D(), AlgDPTotalCosts(), AlgFourHart2D(), AlgFourRealInv3D(), AlgMatrixLUDecompRaw(), AlgMatrixLUDetermRaw(), AlgMatrixLUSolveRaw(), AlgMatrixRSEigen(), AlgMatrixSymNew(), AlgMixtureMLG(), AlgPolynomialLSq(), BibFileEscapeRestrictedChar(), BibFileStrRead(), BibFileUnEscapeRestrictedChar(), main(), nrerror(), Wlz3DSectionSegmentObject(), Wlz3DViewGetBoundingBoxIntersectionA(), Wlz3DViewTransformObj(), WlzAffineTransformLSq2D(), WlzAffineTransformLSqDQ3D(), WlzBasisFnConf2DFromCPts(), WlzBasisFnGauss2DFromCPts(), WlzBasisFnIMQ2DFromCPts(), WlzBasisFnIMQ3DFromCPts(), WlzBasisFnMQ2DFromCPts(), WlzBasisFnMQ3DFromCPts(), WlzBasisFnPoly2DFromCPts(), WlzBasisFnScalarMOS3DFromCPts(), WlzBasisFnTPS2DFromCPts(), WlzBoundaryToPolyObjArray(), WlzBoundObjToPolyDomArray(), WlzCbThreshold(), WlzCentrality(), WlzClipObjToBox2D(), WlzCMeshCompSurfMap(), WlzCMeshCompSurfMapToDomain(), WlzCMeshComputeNormalsIxv2D5(), WlzCMeshDistance2D(), WlzCMeshDistance3D(), WlzCMeshElmMinEdgLnSq3D(), WlzCMeshExpValues(), WlzCMeshFMarNodes2D(), WlzCMeshFMarNodes3D(), WlzCMeshGetBoundNodes2D(), WlzCMeshGetBoundNodes2D5(), WlzCMeshGetBoundNodes3D(), WlzCMeshGetNodesAndEdges(), WlzCMeshLPFilterLM(), WlzCMeshMakeElmIdxTbl2D(), WlzCMeshMakeElmIdxTbl2D5(), WlzCMeshMakeElmIdxTbl3D(), WlzCMeshMakeNodIdxTbl2D(), WlzCMeshMakeNodIdxTbl2D5(), WlzCMeshMakeNodIdxTbl3D(), WlzCMeshRemDelElmCb3D(), WlzCMeshToDomObjValues(), WlzCMeshTransformInvert(), WlzCMeshTransformObj(), WlzCMeshValueTransfer(), WlzCompDispIncGrey(), WlzCompoundArrayToScalar(), WlzContourFromPoints(), WlzContourRBFBndObj3D(), WlzConvexHullVtxD3ToI3(), WlzConvHullClarkson2D(), WlzConvHullClarkson2I(), WlzCopyIndexedValues(), WlzCutObjToValBox2D(), WlzCutObjToValBox3D(), WlzDilation(), WlzDistMetricDirVertex2D(), WlzDistMetricDirVertex3D(), WlzDVerticesFromGM(), WlzDynItvAdd(), WlzEffAnlFileNames(), WlzEffFormatTable(), WlzEffIcsFileNames(), WlzEffNodeEleFileNames(), WlzEffReadObjBmpData2D(), WlzEffReadObjEMT(), WlzEffReadObjMesh(), WlzEffReadObjNodeEle(), WlzEffReadObjPly2(), WlzEffReadObjSlc(), WlzEffReadObjSMesh(), WlzEffReadObjTiff(), WlzEffReadObjVMesh(), WlzEffWriteObjAm(), WlzEffWriteObjEMT(), WlzEffWriteObjMesh(), WlzEffWriteObjNifti(), WlzEffWriteObjNodeEle(), WlzEffWriteObjNrrd(), WlzEffWriteObjObj(), WlzEffWriteObjPly2(), WlzEffWriteObjSlc(), WlzEffWriteObjSMesh(), WlzEffWriteObjStack(), WlzEffWriteObjStl(), WlzEffWriteObjVMesh(), WlzEffWriteObjVtk(), WlzEffWritePointsVtkFieldValues(), WlzErosion(), WlzErosion4(), WlzExplode3D(), WlzExtFFReadObjRaw(), WlzFilterNObjValues(), WlzFromArray1D(), WlzFromArray2D(), WlzFromArray3D(), WlzGauss2(), WlzGaussFilter(), WlzGeomCurvature(), WlzGeometryLSqOPlane(), WlzGeometryTrackUpAndDown_s(), WlzGeomInterpolatePoly2D(), WlzGeomPolyTriangulate2D(), WlzGetProjectionFromObject(), WlzGMFilterGeomLPLM(), WlzGMModelAddResCb(), WlzGMModelFindNMEdges(), WlzGreySetHilbertRankValues(), WlzHistogramCnvGauss(), WlzHistogramConvolve(), WlzHistogramFindPeaks(), WlzHistogramFitPeaks(), WlzHistogramRsvFilter(), WlzIndexObjFromCompound(), WlzIntersect3d(), WlzIntersectN(), WlzIntRescaleObj(), WlzIterate(), WlzLabel(), WlzLabel3D(), WlzMakeBoundList(), WlzMakeConvexHullDomain2(), WlzMakeConvexHullDomain3(), WlzMakeIndexedValues(), WlzMakeIntervalDomain(), WlzMakeIVertex(), WlzMakeMain(), WlzMakePlaneDomain(), WlzMakePointValues(), WlzMakeRectValueTb(), WlzMakeSimpleProperty(), WlzMakeSpecialStructElement(), WlzMakeTiledValueBuffer(), WlzMakeTiledValuesTiles(), WlzMatchICPCtr(), WlzMatchICPWeightMatches(), WlzMeshEarListRealloc(), WlzMeshFromObjBox(), WlzMeshGetNodesAndEdges(), WlzMeshPolyDomAdd(), WlzMeshSqueeze(), WlzMeshTransformFromCPts(), WlzMeshTransformVtx(), WlzNewIDomain(), WlzNewValueTb(), WlzObjectFacts(), WlzObjToBoundary(), WlzObjToConvexHull(), WlzObjToConvexPolygon(), WlzPointValuesFromDomObj(), WlzPolarSample(), WlzPolyTo8Polygon(), WlzPolyToObj(), WlzPrintPatchTree(), WlzRankFilter(), WlzReadMeshTransform3D(), WlzReadObj(), WlzRegCCorObjs(), WlzRegConCalcRCC(), WlzRegICPObjWSD2D(), WlzRegICPVertices(), WlzRegICPVerticesWSD2D(), WlzRsvFilterBuffer(), WlzSampleObj(), WlzSampleObjPoint2D(), WlzSampleValuesAndCoords(), WlzScalarBinaryOp(), WlzScalarFeatures2D(), WlzScalarMulAdd(), WlzSepFilter(), WlzSepTrans(), WlzSkeleton3D(), WlzSnapFit(), WlzSplitObj(), WlzStructDilation(), WlzStructErosion(), WlzThreshold(), WlzToArray1D(), WlzToArray2D(), WlzToArray3D(), WlzTransformRANSAC(), WlzTransposeObj(), WlzUnion3d(), WlzUnionN(), WlzVertexHeapSortIdxFnD3(), WlzVerticesFromObj2I(), WlzVerticesFromObj3I(), WlzVerticesFromObjBnd2I(), and WlzWriteMeshTransform3D().
void* AlcRealloc (void * givenData, size_t byteCount)
Re-allocates space for the given number of bytes with the contents of given data being unchanged.
Returns
Allocated storage or NULL on error.
Parameters
givenData Given storage.
byteCount Number of bytes required.
Referenced by AlcCPQItemUnlink(), AlcHeapInsertEnt(), BibFileEscapeRestrictedChar(), BibFileStrRead(), WlzBasisFnGauss2DFromCPts(), WlzBasisFnIMQ2DFromCPts(), WlzBasisFnIMQ3DFromCPts(), WlzBasisFnMQ2DFromCPts(), WlzBasisFnMQ3DFromCPts(), WlzBasisFnTPS2DFromCPts(), WlzCMeshComputeCurvaturesFromNodNorm(), WlzCMeshElmRingElmIndices2D(), WlzCMeshElmRingElmIndices3D(), WlzCMeshElmRingNodIndices2D(), WlzCMeshElmUseNod3D(), WlzCMeshExpValues(), WlzCMeshMeshMeshProduct(), WlzCMeshNodRingElmIndices2D5(), WlzCMeshNodRingNodIndices2D(), WlzCMeshNodRingNodIndices2D5(), WlzCMeshNodRingNodIndices3D(), WlzCMeshToDomObjValues(), WlzConvexHullVtxD3ToI3(), WlzDrawDomainObj(), WlzEffReadObjSlc(), WlzEffWriteObjSlc(), WlzEffWritePointsVtkFieldValues(), WlzGMModelDeleteV(), WlzGMVertexNormal3D(), WlzKrigReallocBuffers2D(), WlzKrigReallocBuffers3D(), WlzLBTBalanceDomain2D(), WlzLBTBalanceDomain3D(), WlzMatchICPCtr(), WlzMeshExpand(), WlzMeshNodeDelVecBuild(), WlzObjectFacts(), WlzPointsFromDomObj(), and WlzSampleValuesAndCoords().
void AlcFree (void * data)
Free's the given storage.
Returns
void
Parameters
data Given storage.
Referenced by AlcBlockStackFree(), AlcBlockStackNew(), AlcCPQQueueFree(), AlcDLPItemFree(), AlcDLPListFree(), AlcFreeStackFree(), AlcFreeStackPop(), AlcHashItemFree(), AlcHashTableFree(), AlcHashTableNew(), AlcHeapAllEntFree(), AlcHeapFree(), AlcHeapTop(), AlcKDTTreeFree(), AlcLRUCacheFree(), AlcLRUCacheNew(), AlcPtr2Calloc(), AlcPtr2Malloc(), AlcPtr3Calloc(), AlcPtr3Malloc(), AlcUFTreeFree(), AlcUFTreeNew(), AlcVecReadDouble1Asci(), AlcVecReadDouble2Asci(), AlcVectorExtend(), AlcVectorFree(), AlcVectorNew(), AlcVectorToArray2D(), AlgDPTotalCosts(), AlgFourHart2D(), AlgFourRealInv3D(), AlgMatrixLLRExpand(), AlgMatrixLLRFree(), AlgMatrixLUDecompRaw(), AlgMatrixLUDetermRaw(), AlgMatrixLUInvertRaw(), AlgMatrixLUSolveRaw(), AlgMatrixRectFree(), AlgMatrixRectNew(), AlgMatrixRSEigen(), AlgMatrixSolveLSQR(), AlgMatrixSVBackSub(), AlgMatrixSVDecomp(), AlgMatrixSVSolve(), AlgMatrixSymFree(), AlgMatrixSymNew(), AlgMixtureMLG(), AlgPolynomialLSq(), BibFileCharRegEx(), BibFileEscapeRestrictedChar(), BibFileFieldError(), BibFileFieldFree(), BibFileFieldMake(), BibFileFieldRead(), BibFileRecordError(), BibFileRecordFree(), BibFileRecordMake(), BibFileStrRead(), BibFileUnEscapeRestrictedChar(), main(), nrerror(), Wlz3DSectionOcc(), Wlz3DSectionSegmentObject(), Wlz3DViewTransformObj(), WlzAffineTransformLSq2D(), WlzAffineTransformLSqDQ3D(), WlzAffineTransformLSqReg3D(), WlzAffineTransformLSqRegWlz2D(), WlzBasisFnConf2DFromCPts(), WlzBasisFnFree(), WlzBasisFnFreeTransform(), WlzBasisFnGauss2DFromCPts(), WlzBasisFnIMQ2DFromCPts(), WlzBasisFnIMQ3DFromCPts(), WlzBasisFnMQ2DFromCPts(), WlzBasisFnMQ3DFromCPts(), WlzBasisFnPoly2DFromCPts(), WlzBasisFnScalarMOS3DFromCPts(), WlzBasisFnTPS2DFromCPts(), WlzBoundaryToPolyObjArray(), WlzCentrality(), WlzCMeshCompSurfMap(), WlzCMeshCompSurfMapToDomain(), WlzCMeshComputeCurvaturesFromNodNorm(), WlzCMeshComputeNormalsIxv2D5(), WlzCMeshDistance2D(), WlzCMeshDistance3D(), WlzCMeshElmFuse2D(), WlzCMeshElmMinEdgLnSq3D(), WlzCMeshElmUseNod3D(), WlzCMeshExpValues(), WlzCMeshFMarNodes2D(), WlzCMeshFMarNodes3D(), WlzCMeshFree2D(), WlzCMeshFree2D5(), WlzCMeshFree3D(), WlzCMeshGetBoundNodes2D(), WlzCMeshGetBoundNodes2D5(), WlzCMeshGetBoundNodes3D(), WlzCMeshGetNodesAndEdges(), WlzCMeshIndexMaskFromValueRange(), WlzCMeshIntersect2Mesh2D(), WlzCMeshMeshMeshProduct(), WlzCMeshProduct(), WlzCMeshRemDelElmCb3D(), WlzCMeshToDomObjValues(), WlzCMeshTransformInvert(), WlzCMeshTransformManyObjAsIdx(), WlzCMeshTransformObj(), WlzCMeshTrRegSM3D(), WlzCMeshValueTransfer(), WlzCompDispIncGrey(), WlzCompoundArrayToScalar(), WlzCompThreshold(), WlzConComThreshold(), WlzContourFromPoints(), WlzContourRBFBndObj3D(), WlzConvexHullFromVtx2(), WlzConvexHullVtxD3ToI3(), WlzConvHullClarkson2D(), WlzConvHullClarkson2I(), WlzCopyIndexedValues(), WlzCutObjToValBox2D(), WlzCutObjToValBox3D(), WlzDGTensorPDFeature(), WlzDiffDomain(), WlzDilation(), WlzDistMetricDirGM(), WlzDistMetricDirVertex2D(), WlzDistMetricDirVertex3D(), WlzDistMetricGM(), WlzDomainFill3D(), WlzDomainNearby(), WlzDrawDomainObj(), WlzEffFormatTable(), WlzEffReadObjAnl(), WlzEffReadObjBmpData2D(), WlzEffReadObjEMT(), WlzEffReadObjGif(), WlzEffReadObjIcs(), WlzEffReadObjIPL(), WlzEffReadObjJpeg(), WlzEffReadObjNifti(), WlzEffReadObjNodeEle(), WlzEffReadObjNrrd(), WlzEffReadObjPly2(), WlzEffReadObjSlc(), WlzEffReadObjSMesh(), WlzEffReadObjTiff(), WlzEffReadObjVMesh(), WlzEffWriteObjAm(), WlzEffWriteObjAnl(), WlzEffWriteObjBmp2D(), WlzEffWriteObjEMT(), WlzEffWriteObjIcs(), WlzEffWriteObjMesh(), WlzEffWriteObjNifti(), WlzEffWriteObjNodeEle(), WlzEffWriteObjNrrd(), WlzEffWriteObjObj(), WlzEffWriteObjPly2(), WlzEffWriteObjPnm2D(), WlzEffWriteObjPvl(), WlzEffWriteObjSlc(), WlzEffWriteObjSMesh(), WlzEffWriteObjStack(), WlzEffWriteObjVMesh(), WlzEffWriteObjVtk(), WlzEffWritePointsVtkFieldValues(), WlzEffWritePointsVtkScalarValues(), WlzErosion(), WlzErosion4(), WlzExplode3D(), WlzExtFFReadObjRaw(), WlzFilterNObjValues(), WlzFitPlaneSVD(), WlzFree3DViewStruct(), WlzFree3DWarpTrans(), WlzFreeAffineTransform(), WlzFreeBoundList(), WlzFreeContour(), WlzFreeConvexHullDomain2(), WlzFreeConvexHullDomain3(), WlzFreeDomain(), WlzFreeEMAPProperty(), WlzFreeEmptyTransform(), WlzFreeIndexedValues(), WlzFreeLUTValues(), WlzFreeObj(), WlzFreePatchTree(), WlzFreePlaneDomain(), WlzFreePointValues(), WlzFreePolyDmn(), WlzFreeProperty(), WlzFreePropertyList(), WlzFreePropertyListEntry(), WlzFreeSimpleProperty(), WlzFreeTiledValueBuffer(), WlzFreeTiledValues(), WlzFreeValues(), WlzFreeVoxelValueTb(), WlzFromArray1D(), WlzFromArray2D(), WlzFromArray3D(), WlzGauss2(), WlzGaussFilter(), WlzGeomCurvature(), WlzGeometryLSqOPlane(), WlzGeometryTrackUpAndDown_s(), WlzGeomInterpolatePoly2D(), WlzGeoModelGridFree3D(), WlzGeomPolyTriangulate2D(), WlzGetProjectionFromObject(), WlzGMModelDeleteV(), WlzGMModelFree(), WlzGMModelRehashVHT(), WlzGMModelRemResCb(), WlzGMModelResIdxFree(), WlzGreySetHilbertRankValues(), WlzGreyValueFreeWSp(), WlzHistogramCnvGauss(), WlzHistogramConvolve(), WlzHistogramFindPeaks(), WlzHistogramFitPeaks(), WlzHistogramRsvFilter(), WlzIndexObjFromCompound(), WlzInteriorityN(), WlzIntersect3d(), WlzIntersectN(), WlzIterateWSpFree(), WlzLabel(), WlzLabel3D(), WlzLBTDomainToIDomain(), WlzLBTDomainToPDomain(), WlzMake3DViewStructCopy(), WlzMakeAffineTransform(), WlzMakeBoundList(), WlzMakeConvexHullDomain2(), WlzMakeConvexHullDomain3(), WlzMakeCuboid(), WlzMakeGreyProperty(), WlzMakeHistogramDomain(), WlzMakeLUTValues(), WlzMakeMain(), WlzMakeNameProperty(), WlzMakePlaneDomain(), WlzMakePropertyList(), WlzMakeRectValueTb(), WlzMakeSimpleProperty(), WlzMakeTextProperty(), WlzMakeTiledValueBuffer(), WlzMakeTiledValues(), WlzMakeTiledValuesObj2D(), WlzMakeTiledValuesObj3D(), WlzMakeValueTb(), WlzMarkerLattice(), WlzMatchICPCtr(), WlzMatchICPWeightMatches(), WlzMeshEarListRealloc(), WlzMeshElemSplit(), WlzMeshFreeTransform(), WlzMeshFromObjBox(), WlzMeshGetNodesAndEdges(), WlzMeshIDomAdd(), WlzMeshNodeAdd(), WlzMeshNodeDelFree(), WlzMeshPolyDomAdd(), WlzMeshSqueeze(), WlzMeshTransformFromCPts(), WlzMeshTransformNew(), WlzMeshTransformVtx(), WlzMeshVxVecAdd(), WlzObjToBoundary(), WlzObjToConvexHull(), WlzObjToConvexPolygon(), WlzPointsFromDomObj(), WlzPointValuesFromDomObj(), WlzPolarSample(), WlzPolyTo8Polygon(), WlzPolyToObj(), WlzProjectObjToPlane(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzReadMeshTransform3D(), WlzReadObj(), WlzRegCCorObjs(), WlzRegConCalcRCC(), WlzRegICPObjs(), WlzRegICPObjWSD2D(), WlzRegICPVertices(), WlzRegICPVerticesWSD2D(), WlzRemoveProperty(), WlzRsvFilterBuffer(), WlzRsvFilterFreeFilter(), WlzSampleObj(), WlzSampleObjPoint2D(), WlzSampleValuesAndCoords(), WlzScalarBinaryOp(), WlzScalarFeatures2D(), WlzScalarMulAdd(), WlzSepFilter(), WlzSepTrans(), WlzSeqPar(), WlzShadeCorrectBFDF(), WlzSnapFit(), WlzSplitObj(), WlzStructDilation(), WlzStructErosion(), WlzThinToPoints(), WlzToArray1D(), WlzToArray2D(), WlzToArray3D(), WlzTransformRANSAC(), WlzUnion3d(), WlzUnionN(), WlzVertexHeapSortIdxFnD3(), WlzVerticesBuildTree(), WlzVerticesFromObj3I(), and WlzWriteMeshTransform3D().