Woolz Image Processing: WlzStrings
WlzStrings
Files
file WlzStringTypes.c
Functions for converting between Woolz data types and string representations (names) of the types.
file WlzStringUtils.c
Miscellaneous string handling functions.
Functions
const char * WlzStringFromObjType (WlzObject *obj, WlzErrorNum *dstErr)
Finds a string for the given object's type.
const char * WlzStringFromObjTypeValue (WlzObjectType objType, WlzErrorNum *dstErr)
Finds a string for the given object type.
WlzObjectType WlzStringToObjType (const char *oTypeStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given object type string.
const char * WlzStringFromObjDomainType (WlzObject *obj, WlzErrorNum *dstErr)
Finds a string for the given object's domain type.
WlzObjectType WlzStringToObjDomainType (const char *oDomTypeStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given object domain type string.
const char * WlzStringFromObjValuesType (WlzObject *obj, WlzErrorNum *dstErr)
Finds a string for the given object's values type.
WlzObjectType WlzStringToObjValuesType (const char *oValTypeStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given object values type string.
const char * WlzStringFromScalarFeatureType (WlzScalarFeatureType fType, WlzErrorNum *dstErr)
Finds a string for the given scalar feature type.
const char * WlzStringFromPropertyType (WlzProperty prop, WlzErrorNum *dstErr)
Finds a string for the given property's type.
WlzObjectType WlzStringToPropertyType (const char *pStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given property type string.
const char * WlzStringFromEMAPPropertyType (WlzEMAPProperty *eProp, WlzErrorNum *dstErr)
Finds a string for the given EMAP property's type.
WlzEMAPPropertyType WlzStringToEMAPPropertyType (const char *pStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given EMAP property type string.
const char * WlzStringFromTransformType (WlzTransformType tType, WlzErrorNum *dstErr)
Finds a string for the given transform type.
WlzTransformType WlzStringToTransformType (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given transform type string.
const char * WlzStringFromMeshGenMethod (WlzMeshGenMethod mtd, WlzErrorNum *dstErr)
Finds a string for the given mesh generation method.
WlzMeshGenMethod WlzStringToMeshGenMethod (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given mesh generation method.
WlzFnType WlzStringToFnType (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given function type.
const char * WlzStringFromFnType (WlzFnType fn, WlzErrorNum *dstErr)
Finds a string for the given function type.
const char * WlzStringFromGMModelType (WlzGMModelType mType, WlzErrorNum *dstErr)
Finds a string for the given transform type.
WlzGMModelType WlzStringToGMModelType (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given GM model type string.
const char * WlzStringFromGreyType (WlzGreyType gType, WlzErrorNum *dstErr)
Finds a string for the given grey type.
WlzGreyType WlzStringToGreyType (const char *gStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given grey type string.
const char * WlzStringFromVertexType (WlzVertexType vType, WlzErrorNum *dstErr)
Finds a string for the given vertex type.
WlzVertexType WlzStringToVertexType (const char *vStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given vertex type string.
const char * WlzStringFromInterpolationType (WlzInterpolationType iType, WlzErrorNum *dstErr)
Finds a string for the given interpolation type.
WlzInterpolationType WlzStringToInterpolationType (const char *iStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given interpolation type string.
const char * WlzStringFromValueAttachType (WlzValueAttach at, WlzErrorNum *dstErr)
Finds a string for the given values attachment type.
WlzValueAttach WlzStringToValuesAttachType (const char *aStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given values attachment type string.
const char * WlzStringFromThreeDViewMode (WlzThreeDViewMode vMode, WlzErrorNum *dstErr)
Finds a string for the given 3D view mode.
const char * WlzStringFromRCC (WlzRCCClass cls, WlzErrorNum *dstErr)
Finds a string for the given region connected calculus class.
const char * WlzStringFromMarkerType (WlzMarkerType mType, WlzErrorNum *dstErr)
Finds a string for the given values attachment type.
const char * WlzStringFromErrorNum (WlzErrorNum wlzErr, const char **dstMsgStr)
Finds a string for the given error.
WlzErrorNum WlzStringToErrorNum (const char *errStr)
Finds an error number for the given error number string.
int WlzStringMatchValue (int *datum, const char *targetStr, const char *testStr,...)
Given a destination pointer, a string, and a null terminated list of string, enum pairs. The strings are matched and the first match is used to fill in the destination with the matched enum's value.
int WlzValueMatchString (char **datum, int targetVal, const char *testStr,...)
Given a destination pointer, a value, and a null terminated list of string, enum pairs. The values are matched and the first match is used to fill in the destination with the matched enum's string.
char * WlzStringWhiteSpSkip (char *str)
Removes all white space characters (as determined by isspace(3)) from the given string.
char * WlzStringWhiteSpSkipLeading (char *str)
Removes all white space characters (as determined by isspace(3)) from the given string.
char * WlzStringToUpper (char *str)
Converts the string to all upper case using toupper(3).
char * WlzStringToLower (char *str)
Converts the string to all lower case using tolower(3).
Detailed Description
Function Documentation
WlzStringFromObjType()
const char* WlzStringFromObjType (WlzObject * obj, WlzErrorNum * dstErr)
Finds a string for the given object's type.
Returns
Read only string or NULL on error.
Parameters
obj Given object.
dstErr Destination error pointer, may be null.
References _WlzObject::type, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, and WlzStringFromObjTypeValue().
Referenced by WlzStringFromObjValuesType().
WlzStringFromObjTypeValue()
const char* WlzStringFromObjTypeValue (WlzObjectType objType, WlzErrorNum * dstErr)
Finds a string for the given object type.
Returns
Read only string or NULL on error.
Parameters
objType Given object type.
dstErr Destination error pointer, may be null.
References WLZ_2D_DOMAINOBJ, WLZ_2D_POLYGON, WLZ_3D_DOMAINOBJ, WLZ_3D_POLYGON, WLZ_3D_VIEW_STRUCT, WLZ_3D_WARP_TRANS, WLZ_AFFINE_TRANS, WLZ_BOUNDLIST, WLZ_CMESH_2D, WLZ_CMESH_2D5, WLZ_CMESH_3D, WLZ_CMESH_TRANS, WLZ_COMPOUND_ARR_1, WLZ_COMPOUND_ARR_2, WLZ_COMPOUND_LIST_1, WLZ_COMPOUND_LIST_2, WLZ_CONTOUR, WLZ_CONV_HULL, WLZ_CONVOLVE_FLOAT, WLZ_CONVOLVE_INT, WLZ_EMPTY_OBJ, WLZ_ERR_NONE, WLZ_ERR_OBJECT_TYPE, WLZ_FMATCHOBJ, WLZ_HISTOGRAM, WLZ_LUT, WLZ_MESH_TRANS, WLZ_POINTS, WLZ_PROPERTY_OBJ, WLZ_RECTANGLE, WLZ_SPLINE, WLZ_TEXT, WLZ_TRANS_OBJ, and WLZ_WARP_TRANS.
Referenced by WlzStringFromObjType().
WlzStringToObjType()
WlzObjectType WlzStringToObjType (const char * oTypeStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given object type string.
Returns
Woolz object type or WLZ_NULL on error.
Parameters
oTypeStr Given object type string.
dstErr Destination error pointer, may be null.
References WLZ_2D_DOMAINOBJ, WLZ_2D_POLYGON, WLZ_3D_DOMAINOBJ, WLZ_3D_POLYGON, WLZ_3D_VIEW_STRUCT, WLZ_3D_WARP_TRANS, WLZ_AFFINE_TRANS, WLZ_BOUNDLIST, WLZ_CMESH_2D, WLZ_CMESH_2D5, WLZ_CMESH_3D, WLZ_CMESH_TRANS, WLZ_COMPOUND_ARR_1, WLZ_COMPOUND_ARR_2, WLZ_COMPOUND_LIST_1, WLZ_COMPOUND_LIST_2, WLZ_CONTOUR, WLZ_CONV_HULL, WLZ_CONVOLVE_FLOAT, WLZ_CONVOLVE_INT, WLZ_EMPTY_OBJ, WLZ_ERR_NONE, WLZ_ERR_OBJECT_TYPE, WLZ_FMATCHOBJ, WLZ_HISTOGRAM, WLZ_LUT, WLZ_MESH_TRANS, WLZ_NULL, WLZ_POINTS, WLZ_PROPERTY_OBJ, WLZ_RECTANGLE, WLZ_SPLINE, WLZ_TEXT, WLZ_TRANS_OBJ, WLZ_WARP_TRANS, and WlzStringMatchValue().
WlzStringFromObjDomainType()
const char* WlzStringFromObjDomainType (WlzObject * obj, WlzErrorNum * dstErr)
Finds a string for the given object's domain type.
Returns
Pointer to read only string or NULL on error.
Parameters
obj Given object.
dstErr Destination error pointer, may be null.
References _WlzDomain::core, _WlzObject::domain, _WlzObject::type, _WlzCoreDomain::type, WLZ_2D_DOMAINOBJ, WLZ_2D_POLYGON, WLZ_3D_DOMAINOBJ, WLZ_3D_VIEW_STRUCT, WLZ_3D_WARP_TRANS, WLZ_BOUNDLIST, WLZ_BOUNDLIST_HOLE, WLZ_BOUNDLIST_PIECE, WLZ_BSPLINE_C2D, WLZ_BSPLINE_C3D, WLZ_CMESH_2D, WLZ_CMESH_2D5, WLZ_CMESH_3D, WLZ_CONTOUR, WLZ_CONV_HULL, WLZ_CONVHULL_DOMAIN_2D, WLZ_CONVHULL_DOMAIN_3D, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_HISTOGRAM, WLZ_HISTOGRAMDOMAIN_FLOAT, WLZ_HISTOGRAMDOMAIN_INT, WLZ_INTERVALDOMAIN_INTVL, WLZ_INTERVALDOMAIN_RECT, WLZ_LUT, WLZ_PLANEDOMAIN_AFFINE, WLZ_PLANEDOMAIN_BOUNDLIST, WLZ_PLANEDOMAIN_DOMAIN, WLZ_PLANEDOMAIN_HISTOGRAM, WLZ_PLANEDOMAIN_POLYGON, WLZ_PLANEDOMAIN_WARP, WLZ_POINTS, WLZ_POINTS_2D, WLZ_POINTS_2I, WLZ_POINTS_3D, WLZ_POINTS_3I, WLZ_POLYGON_DOUBLE, WLZ_POLYGON_FLOAT, WLZ_POLYGON_INT, WLZ_RECTANGLE, WLZ_RECTANGLE_DOMAIN_FLOAT, WLZ_RECTANGLE_DOMAIN_INT, WLZ_SPLINE, WLZ_TRANS_OBJ, WLZ_TRANSFORM_2D_AFFINE, WLZ_TRANSFORM_3D_AFFINE, and WLZ_WARP_TRANS.
WlzStringToObjDomainType()
WlzObjectType WlzStringToObjDomainType (const char * oDomTypeStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given object domain type string.
Returns
Woolz object type or WLZ_NULL on error.
Parameters
oDomTypeStr Given object domain type string.
dstErr Destination error pointer, may be null.
References WLZ_BOUNDLIST_HOLE, WLZ_BOUNDLIST_PIECE, WLZ_BSPLINE_C2D, WLZ_BSPLINE_C3D, WLZ_CMESH_2D, WLZ_CMESH_2D5, WLZ_CMESH_3D, WLZ_ERR_NONE, WLZ_ERR_OBJECT_TYPE, WLZ_HISTOGRAMDOMAIN_FLOAT, WLZ_HISTOGRAMDOMAIN_INT, WLZ_INTERVALDOMAIN_INTVL, WLZ_INTERVALDOMAIN_RECT, WLZ_LUT, WLZ_NULL, WLZ_PLANEDOMAIN_AFFINE, WLZ_PLANEDOMAIN_BOUNDLIST, WLZ_PLANEDOMAIN_DOMAIN, WLZ_PLANEDOMAIN_HISTOGRAM, WLZ_PLANEDOMAIN_POLYGON, WLZ_PLANEDOMAIN_WARP, WLZ_POINTS_2D, WLZ_POINTS_2I, WLZ_POINTS_3D, WLZ_POINTS_3I, WLZ_POLYGON_DOUBLE, WLZ_POLYGON_FLOAT, WLZ_POLYGON_INT, WLZ_RECTANGLE_DOMAIN_FLOAT, WLZ_RECTANGLE_DOMAIN_INT, WLZ_TRANSFORM_2D_AFFINE, WLZ_TRANSFORM_3D_AFFINE, WLZ_WARP_TRANS, and WlzStringMatchValue().
WlzStringFromObjValuesType()
const char* WlzStringFromObjValuesType (WlzObject * obj, WlzErrorNum * dstErr)
Finds a string for the given object's values type.
Returns
Pointer to read only string or NULL on error.
Parameters
obj Given object.
dstErr Destination error pointer, may be null.
References _WlzValues::core, _WlzValues::obj, _WlzObject::type, _WlzCoreValues::type, _WlzObject::values, WLZ_2D_DOMAINOBJ, WLZ_3D_DOMAINOBJ, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_VALUES_NULL, WLZ_ERR_VALUES_TYPE, WLZ_ERR_VOXELVALUES_TYPE, WLZ_GREY_TAB_INTL, WLZ_GREY_TAB_RAGR, WLZ_GREY_TAB_RECT, WLZ_GREY_TAB_TILED, WLZ_INDEXED_VALUES, WLZ_LUT, WLZ_POINT_VALUES, WLZ_POINTS, WLZ_TRANS_OBJ, WLZ_VALUETABLE_TILED_ARY_BIT, WLZ_VALUETABLE_TILED_ARY_DOUBLE, WLZ_VALUETABLE_TILED_ARY_FLOAT, WLZ_VALUETABLE_TILED_ARY_INT, WLZ_VALUETABLE_TILED_ARY_RGBA, WLZ_VALUETABLE_TILED_ARY_SHORT, WLZ_VALUETABLE_TILED_ARY_UBYTE, WLZ_VALUETABLE_TILED_BIT, WLZ_VALUETABLE_TILED_DOUBLE, WLZ_VALUETABLE_TILED_FLOAT, WLZ_VALUETABLE_TILED_INT, WLZ_VALUETABLE_TILED_RGBA, WLZ_VALUETABLE_TILED_SHORT, WLZ_VALUETABLE_TILED_UBYTE, WLZ_VOXELVALUETABLE_GREY, WlzGreyTableTypeToTableType(), and WlzStringFromObjType().
WlzStringToObjValuesType()
WlzObjectType WlzStringToObjValuesType (const char * oValTypeStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given object values type string.
Returns
Woolz object type or WLZ_NULL on error.
Parameters
oValTypeStr Given object values type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_OBJECT_TYPE, WLZ_GREY_TAB_INTL, WLZ_GREY_TAB_RAGR, WLZ_GREY_TAB_RECT, WLZ_LUT, WLZ_NULL, WLZ_POINT_VALUES, WLZ_VOXELVALUETABLE_GREY, and WlzStringMatchValue().
WlzStringFromScalarFeatureType()
const char* WlzStringFromScalarFeatureType (WlzScalarFeatureType fType, WlzErrorNum * dstErr)
Finds a string for the given scalar feature type.
Returns
Read only string or NULL on error.
Parameters
fType Given scalar feature type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_SCALARFEATURE_GRADIENT, and WLZ_SCALARFEATURE_VALUE.
WlzStringFromPropertyType()
const char* WlzStringFromPropertyType (WlzProperty prop, WlzErrorNum * dstErr)
Finds a string for the given property's type.
Returns
Read only string or NULL on error.
Parameters
prop Given property.
dstErr Destination error pointer, may be null.
References _WlzProperty::core, _WlzCoreProperty::type, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_PROPERTY_TYPE, WLZ_PROPERTY_EMAP, WLZ_PROPERTY_GREY, WLZ_PROPERTY_NAME, WLZ_PROPERTY_SIMPLE, and WLZ_PROPERTY_TEXT.
WlzStringToPropertyType()
WlzObjectType WlzStringToPropertyType (const char * pStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given property type string.
Returns
Woolz property type which will be WLZ_NULL if no matching type is found..
Parameters
pStr Given property type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PROPERTY_TYPE, WLZ_NULL, WLZ_PROPERTY_EMAP, WLZ_PROPERTY_GREY, WLZ_PROPERTY_NAME, WLZ_PROPERTY_SIMPLE, WLZ_PROPERTY_TEXT, and WlzStringMatchValue().
WlzStringFromEMAPPropertyType()
const char* WlzStringFromEMAPPropertyType (WlzEMAPProperty * eProp, WlzErrorNum * dstErr)
Finds a string for the given EMAP property's type.
Returns
Read only string or NULL on error.
Parameters
eProp Given EMAP property.
dstErr Destination error pointer, may be null.
References _WlzEMAPProperty::emapType, WLZ_EMAP_PROPERTY_DOMAIN_ANATOMY, WLZ_EMAP_PROPERTY_DOMAIN_OTHER, WLZ_EMAP_PROPERTY_DUMMY, WLZ_EMAP_PROPERTY_GREY_MODEL, WLZ_EMAP_PROPERTY_GREY_OTHER, WLZ_EMAP_PROPERTY_TRANSFORM, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, and WLZ_ERR_PROPERTY_TYPE.
WlzStringToEMAPPropertyType()
WlzEMAPPropertyType WlzStringToEMAPPropertyType (const char * pStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given EMAP property type string.
Returns
EMAP property type which will be WLZ_EMAP_PROPERTY_DUMMY if no matching type is found..
Parameters
pStr Given property type string.
dstErr Destination error pointer, may be null.
References WLZ_EMAP_PROPERTY_DOMAIN_ANATOMY, WLZ_EMAP_PROPERTY_DOMAIN_OTHER, WLZ_EMAP_PROPERTY_DUMMY, WLZ_EMAP_PROPERTY_GREY_MODEL, WLZ_EMAP_PROPERTY_GREY_OTHER, WLZ_EMAP_PROPERTY_TRANSFORM, WLZ_ERR_NONE, WLZ_ERR_PROPERTY_TYPE, and WlzStringMatchValue().
WlzStringFromTransformType()
const char* WlzStringFromTransformType (WlzTransformType tType, WlzErrorNum * dstErr)
Finds a string for the given transform type.
Returns
Pointer to read only string or NULL on error.
Parameters
tType Given transform type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_TRANSFORM_TYPE, WLZ_TRANSFORM_2D5_BASISFN, WLZ_TRANSFORM_2D5_MESH, WLZ_TRANSFORM_2D_AFFINE, WLZ_TRANSFORM_2D_BASISFN, WLZ_TRANSFORM_2D_CMESH, WLZ_TRANSFORM_2D_MESH, WLZ_TRANSFORM_2D_NOSHEAR, WLZ_TRANSFORM_2D_REG, WLZ_TRANSFORM_2D_TRANS, WLZ_TRANSFORM_3D_AFFINE, WLZ_TRANSFORM_3D_BASISFN, WLZ_TRANSFORM_3D_CMESH, WLZ_TRANSFORM_3D_MESH, WLZ_TRANSFORM_3D_NOSHEAR, WLZ_TRANSFORM_3D_REG, WLZ_TRANSFORM_3D_TRANS, and WLZ_TRANSFORM_EMPTY.
WlzStringToTransformType()
WlzTransformType WlzStringToTransformType (const char * tStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given transform type string.
Returns
Woolz transform type.
Parameters
tStr Given transform type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_TRANSFORM_TYPE, WLZ_TRANSFORM_2D5_BASISFN, WLZ_TRANSFORM_2D5_MESH, WLZ_TRANSFORM_2D_AFFINE, WLZ_TRANSFORM_2D_BASISFN, WLZ_TRANSFORM_2D_CMESH, WLZ_TRANSFORM_2D_MESH, WLZ_TRANSFORM_2D_NOSHEAR, WLZ_TRANSFORM_2D_REG, WLZ_TRANSFORM_2D_TRANS, WLZ_TRANSFORM_3D_AFFINE, WLZ_TRANSFORM_3D_BASISFN, WLZ_TRANSFORM_3D_CMESH, WLZ_TRANSFORM_3D_MESH, WLZ_TRANSFORM_3D_NOSHEAR, WLZ_TRANSFORM_3D_REG, WLZ_TRANSFORM_3D_TRANS, WLZ_TRANSFORM_EMPTY, and WlzStringMatchValue().
WlzStringFromMeshGenMethod()
const char* WlzStringFromMeshGenMethod (WlzMeshGenMethod mtd, WlzErrorNum * dstErr)
Finds a string for the given mesh generation method.
Returns
Pointer to read only string or NULL on error.
Parameters
mtd Given mesh generation method.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_MESH_GENMETHOD_BLOCK, WLZ_MESH_GENMETHOD_CONFORM, and WLZ_MESH_GENMETHOD_GRADIENT.
WlzStringToMeshGenMethod()
WlzMeshGenMethod WlzStringToMeshGenMethod (const char * tStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given mesh generation method.
Returns
Woolz mesh generation method.
Parameters
tStr Given mesh generation string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_TRANSFORM_TYPE, WLZ_MESH_GENMETHOD_BLOCK, WLZ_MESH_GENMETHOD_CONFORM, WLZ_MESH_GENMETHOD_GRADIENT, and WlzStringMatchValue().
WlzStringToFnType()
WlzFnType WlzStringToFnType (const char * tStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given function type.
Returns
Woolz function type.
Parameters
tStr Given function type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_TRANSFORM_TYPE, WLZ_FN_BASIS_2DCONF_POLY, WLZ_FN_BASIS_2DGAUSS, WLZ_FN_BASIS_2DIMQ, WLZ_FN_BASIS_2DMQ, WLZ_FN_BASIS_2DPOLY, WLZ_FN_BASIS_2DTPS, WLZ_FN_BASIS_3DCONF_POLY, WLZ_FN_BASIS_3DGAUSS, WLZ_FN_BASIS_3DIMQ, WLZ_FN_BASIS_3DMOS, WLZ_FN_BASIS_3DMQ, WLZ_FN_BASIS_3DPOLY, WLZ_FN_BASIS_3DTPS, WLZ_FN_BASIS_SCALAR_3DMOS, and WlzStringMatchValue().
WlzStringFromFnType()
const char* WlzStringFromFnType (WlzFnType fn, WlzErrorNum * dstErr)
Finds a string for the given function type.
Returns
Pointer to read only string or NULL on error.
Parameters
fn Given function type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_FN_BASIS_2DCONF_POLY, WLZ_FN_BASIS_2DGAUSS, WLZ_FN_BASIS_2DIMQ, WLZ_FN_BASIS_2DMQ, WLZ_FN_BASIS_2DPOLY, WLZ_FN_BASIS_2DTPS, WLZ_FN_BASIS_3DCONF_POLY, WLZ_FN_BASIS_3DGAUSS, WLZ_FN_BASIS_3DIMQ, WLZ_FN_BASIS_3DMOS, WLZ_FN_BASIS_3DMQ, WLZ_FN_BASIS_3DPOLY, WLZ_FN_BASIS_3DTPS, and WLZ_FN_BASIS_SCALAR_3DMOS.
WlzStringFromGMModelType()
const char* WlzStringFromGMModelType (WlzGMModelType mType, WlzErrorNum * dstErr)
Finds a string for the given transform type.
Returns
Pointer to read only string or NULL on error.
Parameters
mType Given model type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_NONE, WLZ_GMMOD_2D, WLZ_GMMOD_2I, WLZ_GMMOD_2N, WLZ_GMMOD_3D, WLZ_GMMOD_3I, and WLZ_GMMOD_3N.
WlzStringToGMModelType()
WlzGMModelType WlzStringToGMModelType (const char * tStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given GM model type string.
Returns
Woolz GM model type.
Parameters
tStr Given GM Model type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_NONE, WLZ_GMMOD_2D, WLZ_GMMOD_2I, WLZ_GMMOD_2N, WLZ_GMMOD_3D, WLZ_GMMOD_3I, WLZ_GMMOD_3N, and WlzStringMatchValue().
WlzStringFromGreyType()
const char* WlzStringFromGreyType (WlzGreyType gType, WlzErrorNum * dstErr)
Finds a string for the given grey type.
Returns
Pointer to read only string or NULL on error.
Parameters
gType Given grey type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_GREY_TYPE, WLZ_ERR_NONE, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_RGBA, WLZ_GREY_SHORT, and WLZ_GREY_UBYTE.
WlzStringToGreyType()
WlzGreyType WlzStringToGreyType (const char * gStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given grey type string.
Returns
Woolz grey type or WLZ_GREY_ERROR on error.
Parameters
gStr Given grey type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_GREY_TYPE, WLZ_ERR_NONE, WLZ_GREY_DOUBLE, WLZ_GREY_ERROR, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_RGBA, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, and WlzStringMatchValue().
WlzStringFromVertexType()
const char* WlzStringFromVertexType (WlzVertexType vType, WlzErrorNum * dstErr)
Finds a string for the given vertex type.
Returns
Pointer to read only string or NULL on error.
Parameters
vType Given vertex type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_TYPE, WLZ_VERTEX_D2, WLZ_VERTEX_D3, WLZ_VERTEX_F2, WLZ_VERTEX_F3, WLZ_VERTEX_I2, WLZ_VERTEX_I3, WLZ_VERTEX_L2, and WLZ_VERTEX_L3.
WlzStringToVertexType()
WlzVertexType WlzStringToVertexType (const char * vStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given vertex type string.
Returns
Woolz vertex type or WLZ_VERTEX_ERROR on error.
Parameters
vStr Given vertex type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_TYPE, WLZ_VERTEX_D2, WLZ_VERTEX_D3, WLZ_VERTEX_ERROR, WLZ_VERTEX_F2, WLZ_VERTEX_F3, WLZ_VERTEX_I2, WLZ_VERTEX_I3, WLZ_VERTEX_L2, WLZ_VERTEX_L3, and WlzStringMatchValue().
WlzStringFromInterpolationType()
const char* WlzStringFromInterpolationType (WlzInterpolationType iType, WlzErrorNum * dstErr)
Finds a string for the given interpolation type.
Returns
Pointer to read only string or NULL on error.
Parameters
iType Given interpolation type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_INTERPOLATION_CALLBACK, WLZ_INTERPOLATION_CLASSIFY_1, WLZ_INTERPOLATION_LINEAR, and WLZ_INTERPOLATION_NEAREST.
WlzStringToInterpolationType()
WlzInterpolationType WlzStringToInterpolationType (const char * iStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given interpolation type string.
Returns
Woolz interpolation type.
Parameters
iStr Given interpolation type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_INTERPOLATION_CALLBACK, WLZ_INTERPOLATION_CLASSIFY_1, WLZ_INTERPOLATION_LINEAR, WLZ_INTERPOLATION_NEAREST, and WlzStringMatchValue().
WlzStringFromValueAttachType()
const char* WlzStringFromValueAttachType (WlzValueAttach at, WlzErrorNum * dstErr)
Finds a string for the given values attachment type.
Returns
Pointer to read only string or NULL on error.
Parameters
at Given values attachment type.
dstErr Destination error pointer, may be null.
WlzStringToValuesAttachType()
WlzValueAttach WlzStringToValuesAttachType (const char * aStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given values attachment type string.
Returns
Woolz values attachment type.
Parameters
aStr Given values attachment type string.
dstErr Destination error pointer, may be null.
WlzStringFromThreeDViewMode()
const char* WlzStringFromThreeDViewMode (WlzThreeDViewMode vMode, WlzErrorNum * dstErr)
Finds a string for the given 3D view mode.
Returns
Pointer to read only string or NULL on error.
Parameters
vMode Given 3D view mode.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_FIXED_LINE_MODE, WLZ_STATUE_MODE, WLZ_UP_IS_UP_MODE, WLZ_ZERO_ZETA_MODE, and WLZ_ZETA_MODE.
WlzStringFromRCC()
const char* WlzStringFromRCC (WlzRCCClass cls, WlzErrorNum * dstErr)
Finds a string for the given region connected calculus class.
Returns
Pointer to read only string or NULL on error.
Parameters
cls Given RCC class.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_RCC_DC, WLZ_RCC_EC, WLZ_RCC_EMPTY, WLZ_RCC_ENC, WLZ_RCC_ENCI, WLZ_RCC_EQ, WLZ_RCC_NTPP, WLZ_RCC_NTPPI, WLZ_RCC_NTSUR, WLZ_RCC_NTSURI, WLZ_RCC_OST, WLZ_RCC_PO, WLZ_RCC_TPP, WLZ_RCC_TPPI, WLZ_RCC_TSUR, and WLZ_RCC_TSURI.
WlzStringFromMarkerType()
const char* WlzStringFromMarkerType (WlzMarkerType mType, WlzErrorNum * dstErr)
Finds a string for the given values attachment type.
Returns
Pointer to read only string or NULL on error.
Parameters
mType Given values attachment type.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_DATA, WLZ_MARKER_NONE, WLZ_MARKER_POINT, and WLZ_MARKER_SPHERE.
WlzStringFromErrorNum()
const char* WlzStringFromErrorNum (WlzErrorNum wlzErr, const char ** dstMsgStr)
Finds a string for the given error.
Returns
Pointer to read only string or NULL on error.
Parameters
wlzErr Given error code.
dstMsgStr Destination pointer for a 'meaningful' message string, may be NULL.
References WLZ_ERR_ALG, WLZ_ERR_ALG_CONDITION, WLZ_ERR_ALG_CONVERGENCE, WLZ_ERR_ALG_HOMOGENEOUS, WLZ_ERR_ALG_NONGLOBAL, WLZ_ERR_ALG_SINGULAR, WLZ_ERR_BINARY_OPERATOR_TYPE, WLZ_ERR_COLUMN_DATA, WLZ_ERR_COMPTHRESH_TYPE, WLZ_ERR_CONNECTIVITY_TYPE, WLZ_ERR_DEGENERATE, WLZ_ERR_DOMAIN_DATA, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_DOUBLE_DATA, WLZ_ERR_EOO, WLZ_ERR_FILE_FORMAT, WLZ_ERR_FILE_OPEN, WLZ_ERR_FLOAT_DATA, WLZ_ERR_GMELM_DATA, WLZ_ERR_GMELM_NULL, WLZ_ERR_GMELM_TYPE, WLZ_ERR_GREY_DATA, WLZ_ERR_GREY_TYPE, WLZ_ERR_IMAGE_TYPE, WLZ_ERR_INT_DATA, WLZ_ERR_INTERPOLATION_TYPE, WLZ_ERR_INTERVAL_ADJACENT, WLZ_ERR_INTERVAL_BOUND, WLZ_ERR_INTERVAL_DATA, WLZ_ERR_INTERVAL_NULL, WLZ_ERR_INTERVAL_NUMBER, WLZ_ERR_INTERVALDOMAIN_NULL, WLZ_ERR_INTERVALDOMAIN_TYPE, WLZ_ERR_INTERVALLINE_NULL, WLZ_ERR_LINE_DATA, WLZ_ERR_LINKCOUNT_DATA, WLZ_ERR_MEM_ALLOC, WLZ_ERR_MEM_FREE, WLZ_ERR_NONE, WLZ_ERR_OBJECT_DATA, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_PARAM_DATA, WLZ_ERR_PARAM_NULL, WLZ_ERR_PARAM_TYPE, WLZ_ERR_PLANE_DATA, WLZ_ERR_PLANEDOMAIN_DATA, WLZ_ERR_PLANEDOMAIN_TYPE, WLZ_ERR_POLYGON_TYPE, WLZ_ERR_PROPERTY_NULL, WLZ_ERR_RASTERDIR_TYPE, WLZ_ERR_READ_EOF, WLZ_ERR_READ_INCOMPLETE, WLZ_ERR_SHORT_DATA, WLZ_ERR_TRANSFORM_DATA, WLZ_ERR_TRANSFORM_NULL, WLZ_ERR_TRANSFORM_TYPE, WLZ_ERR_UBYTE_DATA, WLZ_ERR_UNIMPLEMENTED, WLZ_ERR_UNSPECIFIED, WLZ_ERR_VALUES_DATA, WLZ_ERR_VALUES_NULL, WLZ_ERR_VALUES_TYPE, WLZ_ERR_VOXELVALUES_TYPE, WLZ_ERR_WRITE_EOF, and WLZ_ERR_WRITE_INCOMPLETE.
WlzStringToErrorNum()
WlzErrorNum WlzStringToErrorNum (const char * errStr)
Finds an error number for the given error number string.
Returns
Matched error number.
Parameters
errStr Given error number string.
References WLZ_ERR_ALG, WLZ_ERR_ALG_CONVERGENCE, WLZ_ERR_ALG_HOMOGENEOUS, WLZ_ERR_ALG_NONGLOBAL, WLZ_ERR_ALG_SINGULAR, WLZ_ERR_BINARY_OPERATOR_TYPE, WLZ_ERR_COLUMN_DATA, WLZ_ERR_COMPTHRESH_TYPE, WLZ_ERR_CONNECTIVITY_TYPE, WLZ_ERR_DEGENERATE, WLZ_ERR_DOMAIN_DATA, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_DOUBLE_DATA, WLZ_ERR_EOO, WLZ_ERR_FILE_FORMAT, WLZ_ERR_FILE_OPEN, WLZ_ERR_FLOAT_DATA, WLZ_ERR_GMELM_DATA, WLZ_ERR_GMELM_NULL, WLZ_ERR_GMELM_TYPE, WLZ_ERR_GREY_DATA, WLZ_ERR_GREY_TYPE, WLZ_ERR_IMAGE_TYPE, WLZ_ERR_INT_DATA, WLZ_ERR_INTERPOLATION_TYPE, WLZ_ERR_INTERVAL_ADJACENT, WLZ_ERR_INTERVAL_BOUND, WLZ_ERR_INTERVAL_DATA, WLZ_ERR_INTERVAL_NULL, WLZ_ERR_INTERVAL_NUMBER, WLZ_ERR_INTERVALDOMAIN_NULL, WLZ_ERR_INTERVALDOMAIN_TYPE, WLZ_ERR_INTERVALLINE_NULL, WLZ_ERR_LINE_DATA, WLZ_ERR_LINKCOUNT_DATA, WLZ_ERR_MEM_ALLOC, WLZ_ERR_MEM_FREE, WLZ_ERR_NONE, WLZ_ERR_OBJECT_DATA, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_PARAM_DATA, WLZ_ERR_PARAM_NULL, WLZ_ERR_PARAM_TYPE, WLZ_ERR_PLANE_DATA, WLZ_ERR_PLANEDOMAIN_DATA, WLZ_ERR_PLANEDOMAIN_TYPE, WLZ_ERR_POLYGON_TYPE, WLZ_ERR_PROPERTY_NULL, WLZ_ERR_RASTERDIR_TYPE, WLZ_ERR_READ_EOF, WLZ_ERR_READ_INCOMPLETE, WLZ_ERR_SHORT_DATA, WLZ_ERR_TRANSFORM_DATA, WLZ_ERR_TRANSFORM_NULL, WLZ_ERR_TRANSFORM_TYPE, WLZ_ERR_UBYTE_DATA, WLZ_ERR_UNIMPLEMENTED, WLZ_ERR_UNSPECIFIED, WLZ_ERR_VALUES_DATA, WLZ_ERR_VALUES_NULL, WLZ_ERR_VALUES_TYPE, WLZ_ERR_VOXELVALUES_TYPE, WLZ_ERR_WRITE_EOF, WLZ_ERR_WRITE_INCOMPLETE, and WlzStringMatchValue().
WlzStringMatchValue()
int WlzStringMatchValue (int * datum, const char * targetStr, const char * testStr, ...)
Given a destination pointer, a string, and a null terminated list of string, enum pairs. The strings are matched and the first match is used to fill in the destination with the matched enum's value.
Returns
Zero if no match found.
Parameters
datum Pointer to datum for return.
targetStr String to match.
testStr First string of the list.
... NULL terminated varargs list of strings (char *) and enum (int) pairs.
References WLZ_DBG, WLZ_DBG_LVL_3, and WLZ_DBG_LVL_FN.
Referenced by WlzEffBibParseWarpInputThresholdParamsRecord(), WlzEffReadObjIcs(), WlzEffStringExtToFormat(), WlzEffStringToFormat(), WlzStringToEMAPPropertyType(), WlzStringToErrorNum(), WlzStringToFnType(), WlzStringToGMModelType(), WlzStringToGreyType(), WlzStringToInterpolationType(), WlzStringToMarkerType(), WlzStringToMeshGenMethod(), WlzStringToObjDomainType(), WlzStringToObjType(), WlzStringToObjValuesType(), WlzStringToPropertyType(), WlzStringToRCCClass(), WlzStringToScalarFeatureType(), WlzStringToThreeDViewMode(), WlzStringToTransformType(), WlzStringToVertexType(), and WlzWindowFnValue().
WlzValueMatchString()
int WlzValueMatchString (char ** datum, int targetVal, const char * testStr, ...)
Given a destination pointer, a value, and a null terminated list of string, enum pairs. The values are matched and the first match is used to fill in the destination with the matched enum's string.
Returns
Zero if no match found.
Parameters
datum Pointer to string for return.
targetVal Value to match.
testStr First string of the list.
... NULL terminated varargs list of strings (char *) and enum (int) pairs.
Referenced by WlzEffBibWriteWarpInputThresholdParamsRecord().
WlzStringWhiteSpSkip()
char* WlzStringWhiteSpSkip (char * str)
Removes all white space characters (as determined by isspace(3)) from the given string.
Returns
The given string.
Parameters
str Given string.
WlzStringWhiteSpSkipLeading()
char* WlzStringWhiteSpSkipLeading (char * str)
Removes all white space characters (as determined by isspace(3)) from the given string.
Returns
The given string.
Parameters
str Given string.
WlzStringToUpper()
char* WlzStringToUpper (char * str)
Converts the string to all upper case using toupper(3).
Returns
The given string.
Parameters
str Given string.
WlzStringToLower()
char* WlzStringToLower (char * str)
Converts the string to all lower case using tolower(3).
Returns
The given string.
Parameters
str Given string.