Woolz Image Processing: AlgCorr
AlgCorr
Files
file AlgAutoCorr.c
Frequency domain auto correlation functions.
file AlgCrossCorr.c
Frequency domain cross correlation functions.
Functions
AlgError AlgCrossCorrelate2D (double **data0, double **data1, int nX, int nY)
Cross correlates the given 2D double arrays leaving the result in the first of the two arrays. The cross correlation data are un-normalized.
void AlgCrossCorrPeakXY (int *dstMaxX, int *dstMaxY, double *dstMaxVal, double **data, int nX, int nY, int searchX, int searchY)
Find the maximum correlation value in the given two dimensional array. Because the correlation data are stored in wrap-around order and the maximum is known to lie within a limited search range, only the four corners of the array are searched.
Detailed Description
Function Documentation
AlgCrossCorrelate2D()
AlgError AlgCrossCorrelate2D (double ** data0, double ** data1, int nX, int nY)
Cross correlates the given 2D double arrays leaving the result in the first of the two arrays. The cross correlation data are un-normalized.
Returns
Error code.
Parameters
data0 Data for/with obj0's FFT (source: AlcDouble2Malloc) which holds the cross
correlation data on return.
data1 Data for/with obj1's FFT (source: AlcDouble2Malloc).
nX Number of columns in each of the data arrays.
nY Number of lines in each of the data arrays.
References ALG_ERR_FUNC, ALG_ERR_NONE, AlgBitNextPowerOfTwo(), AlgFourReal2D(), and AlgFourRealInv2D().
AlgCrossCorrPeakXY()
void AlgCrossCorrPeakXY (int * dstMaxX, int * dstMaxY, double * dstMaxVal, double ** data, int nX, int nY, int searchX, int searchY)
Find the maximum correlation value in the given two dimensional array. Because the correlation data are stored in wrap-around order and the maximum is known to lie within a limited search range, only the four corners of the array are searched.
Returns
void
Parameters
dstMaxX Destination ptr for column coordinate with maximum value.
dstMaxY Destination ptr for line coordinate with maximum value.
dstMaxVal Destination ptr for maximum value.
data Data to search for maximum.
nX Number of colimns in data.
nY Number of lines in data.
searchX Maximum number of columns to search.
searchY Maximum number of lines to search.