Woolz Image Processing: WlzDebug
WlzDebug
Files
file WlzDebug.c
Default debugging text and object output functions for the Woolz library flag based debugging system.
file WlzDebug.h
Defines the Woolz debug masks and function prototypes.
file WlzFacts.c
Text description (facts) of Woolz objects.
file WlzVersion.c
Simple Woolz versioning.
Enumerations
enum _WlzDbgMask {
WLZ_DBG_NONE = (0),
WLZ_DBG_LVL_1 = (1),
WLZ_DBG_LVL_2 = (1<<1),
WLZ_DBG_LVL_3 = (1<<2),
WLZ_DBG_LVL_FN = (1<<3),
WLZ_DBG_ALLOC = (1<<4)
}
Woolz debug bit masks. Typedef: WlzDbgMask.
Functions
WlzErrorNum WlzDbgWrite (char *fmt,...)
Writes out the given debug message to the debug file.
WlzErrorNum WlzDbgObjWrite (WlzObject *obj, int freeFlg)
Writes out the given debug Woolz object to the woolz debug file.
WlzErrorNum WlzObjectFacts (WlzObject *obj, FILE *factsFile, char **dstStr, int verbose)
The external facts interface function. Creates the facts data structure and then produces a text description of the given object.
const char * WlzVersion ()
Returns the current version of Woolz.
Detailed Description
Enumeration Type Documentation
enum _WlzDbgMask
Woolz debug bit masks. Typedef: WlzDbgMask.
Enumerator
WLZ_DBG_NONE
No debug output
WLZ_DBG_LVL_1
Least debug output
WLZ_DBG_LVL_2
Intermediate debug output
WLZ_DBG_LVL_3
Most debug output
WLZ_DBG_LVL_FN
Function entry and return
WLZ_DBG_ALLOC
Allocation and freeing
Function Documentation
WlzErrorNum WlzDbgWrite (char * fmt, ...)
Writes out the given debug message to the debug file.
Returns
Woolz error code.
Parameters
fmt Format for printing message.
References WLZ_ERR_NONE, WLZ_ERR_UNSPECIFIED, and wlzDbgData.
WlzErrorNum WlzDbgObjWrite (WlzObject * obj, int freeFlg)
Writes out the given debug Woolz object to the woolz debug file.
Returns
Woolz error code.
Parameters
obj Woolz debug object for output.
freeFlg If non zero free the object after writing it.
References WLZ_ERR_NONE, WLZ_ERR_UNSPECIFIED, wlzDbgObjData, WlzFreeObj(), and WlzWriteObj().
WlzErrorNum WlzObjectFacts (WlzObject * obj, FILE * factsFile, char ** dstStr, int verbose)
The external facts interface function. Creates the facts data structure and then produces a text description of the given object.
Returns
Woolz error code.
Parameters
obj The given object.
factsFile If non-NULL the text is written to the given file.
dstStr If non-NULL the pointer is set to an allocated text string, which should be free'd using AlcFree().
verbose Verbose output if non-zero.
References AlcMalloc(), AlcRealloc(), AlcVectorItemGet(), _WlzEMAPProperty::anatomyUID, _WlzIndexedValues::attach, _WlzDomain::b, _WlzGMShellG2I::bBox, _WlzGMShellG2D::bBox, _WlzGMShellG3I::bBox, _WlzGMShellG3D::bBox, _WlzRagRValues::bckgrnd, _WlzRectValues::bckgrnd, _WlzIntervalValues::bckgrnd, _WlzVoxelValues::bckgrnd, _WlzTiledValues::bckgrnd, _WlzLUTDomain::bin1, _WlzHistogramDomain::binSize, _WlzConvHullDomain2::centroid, _WlzConvHullDomain3::centroid, _WlzDomain::cm2, _WlzDomain::cm2d5, _WlzDomain::cm3, _WlzEMAPProperty::comment, _WlzGMShellGU::core, _WlzValues::core, _WlzDomain::core, _WlzProperty::core, _WlzEMAPProperty::creationAuthor, _WlzEMAPProperty::creationMachineName, _WlzEMAPProperty::creationTime, _WlzDomain::ctr, _WlzDomain::cvh2, _WlzDomain::cvh3, _WlzVertexP::d2, _WlzVertex::d2, _WlzVertexP::d3, _WlzVertex::d3, _WlzGreyP::dbp, _WlzGreyV::dbv, _WlzIndexedValues::dim, _WlzPointValues::dim, _WlzGMModelR::diskT, _WlzThreeDViewStruct::dist, _WlzObject::domain, _WlzPlaneDomain::domains, _WlzBoundList::down, _WlzCMeshEntP::e2, _WlzCMeshEntP::e2d5, _WlzCMeshEntP::e3, _WlzGMModelR::edge, _WlzGMModelR::edgeT, _WlzCMeshFace::edu, _WlzCMeshElm2D::edu, _WlzCMeshElm2D5::edu, _WlzCMeshRes::elm, _WlzProperty::emap, _AlcDLPItem::entry, _WlzVertex::f2, _WlzGMModelR::face, _WlzCMeshElm3D::face, _WlzConvHullDomain3::faces, _WlzTiledValues::fd, WlzObjFactsData::fFile, _WlzEMAPProperty::fileName, _WlzThreeDViewStruct::fixed, _WlzThreeDViewStruct::fixed_2, _WlzThreeDViewStruct::fixed_line_angle, _WlzGreyP::flp, _WlzGreyV::flv, WlzObjFactsData::fStr, WlzObjFactsData::fStrInc, WlzObjFactsData::fStrLen, WlzObjFactsData::fStrMax, _WlzGMShell::geo, _WlzProperty::greyV, _AlcDLPList::head, _WlzDomain::hist, _WlzValues::i, _WlzDomain::i, _WlzVertexP::i2, _WlzVertex::i2, _WlzVertexP::i3, _WlzVertex::i3, _WlzGMShell::idx, _WlzCMeshNod2D::idx, _WlzCMeshNod2D5::idx, _WlzCMeshNod3D::idx, _WlzCMeshElm2D::idx, _WlzCMeshElm2D5::idx, _WlzCMeshElm3D::idx, _WlzInterval::ileft, WlzObjFactsData::indent, _WlzGreyP::inp, _WlzThreeDViewStruct::interp, _WlzIntervalDomain::intvlines, _WlzIntervalLine::intvs, _WlzGreyV::inv, _WlzInterval::iright, _WlzIntervalDomain::kol1, _WlzPlaneDomain::kol1, _WlzRagRValues::kol1, _WlzRectValues::kol1, _WlzIntervalValues::kol1, _WlzTiledValues::kol1, _WlzVertex::l2, _WlzLUTDomain::lastbin, _WlzIntervalDomain::lastkl, _WlzPlaneDomain::lastkl, _WlzTiledValues::lastkl, _WlzIntervalDomain::lastln, _WlzPlaneDomain::lastln, _WlzRagRValues::lastln, _WlzRectValues::lastln, _WlzIntervalValues::lastln, _WlzTiledValues::lastln, _WlzPlaneDomain::lastpl, _WlzVoxelValues::lastpl, _WlzTiledValues::lastpl, _WlzIntervalDomain::line1, _WlzPlaneDomain::line1, _WlzRagRValues::line1, _WlzRectValues::line1, _WlzIntervalValues::line1, _WlzTiledValues::line1, _WlzGMModel::linkcount, _WlzContour::linkcount, _WlzLUTDomain::linkcount, _WlzCoreProperty::linkcount, _WlzObject::linkcount, _WlzCoreDomain::linkcount, _WlzIntervalDomain::linkcount, _WlzCoreValues::linkcount, _WlzLUTValues::linkcount, _WlzPointValues::linkcount, _WlzPoints::linkcount, _WlzPolygonDomain::linkcount, _WlzBoundList::linkcount, _WlzHistogramDomain::linkcount, _WlzCMesh2D::linkcount, _WlzCMesh2D5::linkcount, _WlzCMesh3D::linkcount, _WlzAffineTransform::linkcount, _WlzMeshTransform::linkcount, _WlzThreeDViewStruct::linkcount, _WlzPropertyList::list, _WlzGreyP::lnp, _WlzGreyV::lnv, _WlzGMModelR::loopT, _WlzValues::lut, _WlzDomain::lut, _WlzCMeshP::m2, _WlzCMeshP::m2d5, _WlzCMeshP::m3, _WlzAffineTransform::mat, _WlzCMeshEntRes::maxEnt, _WlzConvHullDomain3::maxFaces, _WlzPointValues::maxPoints, _WlzPoints::maxPoints, _WlzLUTValues::maxVal, _WlzThreeDViewStruct::maxvals, _WlzPolygonDomain::maxvertices, _WlzConvHullDomain2::maxVertices, _WlzConvHullDomain3::maxVertices, _WlzThreeDViewStruct::minvals, _WlzContour::model, _WlzEMAPProperty::modelName, _WlzEMAPProperty::modelUID, _WlzEMAPProperty::modificationAuthor, _WlzEMAPProperty::modificationTime, _WlzDomain::mt, _WlzCompoundArray::n, _WlzCMeshEntP::n2, _WlzCMeshEntP::n2d5, _WlzCMeshEntP::n3, _WlzNameProperty::name, _WlzGreyProperty::name, _WlzTextProperty::name, _WlzProperty::name, _WlzHistogramDomain::nBins, _WlzMeshTransform::nElem, _AlcDLPItem::next, _WlzBoundList::next, _WlzConvHullDomain3::nFaces, _WlzIntervalLine::nintvs, _WlzMeshTransform::nNodes, _WlzCMeshEdgU2D::nod, _WlzCMeshEdgU2D5::nod, _WlzCMeshEdgU3D::nod, _WlzCMeshRes::nod, _WlzPoints::nPoints, _WlzGMResource::numElm, _WlzCMeshEntRes::numEnt, _WlzGMResource::numIdx, _WlzTiledValues::numTiles, _WlzPolygonDomain::nvertices, _WlzConvHullDomain2::nVertices, _WlzConvHullDomain3::nVertices, _WlzCompoundArray::o, _WlzValues::obj, _WlzHistogramDomain::origin, _WlzCompoundArray::otype, _WlzDomain::p, _WlzThreeDViewStruct::phi, _WlzPlaneDomain::plane1, _WlzVoxelValues::plane1, _WlzTiledValues::plane1, _WlzObject::plist, _WlzCompoundArray::plist, _WlzPoints::points, _WlzDomain::poly, _WlzBoundList::poly, _WlzCMeshNod2D::pos, _WlzCMeshNod2D5::pos, _WlzCMeshNod3D::pos, _WlzValues::pts, _WlzDomain::pts, _WlzValues::r, _WlzIndexedValues::rank, _WlzPointValues::rank, _WlzGMModel::res, _WlzCMesh2D::res, _WlzCMesh2D5::res, _WlzCMesh3D::res, _WlzGreyP::rgbp, _WlzGreyV::rgbv, _WlzThreeDViewStruct::scale, _WlzGMShellGU::sg2D, _WlzGMShellGU::sg2I, _WlzGMShellGU::sg3D, _WlzGMShellGU::sg3I, _WlzGMModelR::shell, _WlzGMModelR::shellG, _WlzGreyP::shp, _WlzGreyV::shv, _WlzProperty::simple, _WlzSimpleProperty::size, _WlzEMAPProperty::stage, _WlzEMAPProperty::subStage, _WlzValues::t, _WlzDomain::t, _WlzEMAPProperty::targetUID, _WlzEMAPProperty::targetVersion, _WlzTextProperty::text, _WlzProperty::text, _WlzThreeDViewStruct::theta, _WlzTiledValues::tileOffset, _WlzTiledValues::tileSz, _WlzTiledValues::tileWidth, _WlzThreeDViewStruct::trans, _WlzPixelV::type, _WlzGMCore::type, _WlzGMModel::type, _WlzCoreProperty::type, _WlzEMAPProperty::type, _WlzObject::type, _WlzCoreDomain::type, _WlzIntervalDomain::type, _WlzCoreValues::type, _WlzPointValues::type, _WlzPoints::type, _WlzPolygonDomain::type, _WlzBoundList::type, _WlzAffineTransform::type, _WlzMeshTransform::type, _WlzThreeDViewStruct::type, _WlzGreyP::ubp, _WlzGreyV::ubv, _WlzThreeDViewStruct::up, _WlzVertexP::v, _WlzGreyP::v, _WlzPixelV::v, _WlzValues::v, _WlzCMeshEntP::v, _WlzLUTValues::val, _WlzGreyProperty::value, _WlzObject::values, _WlzVoxelValues::values, _WlzPointValues::values, _WlzTiledValues::vDim, _WlzGMResource::vec, _WlzCMeshEntRes::vec, WlzObjFactsData::verbose, _WlzEMAPProperty::version, _WlzGMModelR::vertex, _WlzGMModelR::vertexG, _WlzGMModelR::vertexT, _WlzConvHullDomain2::vertices, _WlzConvHullDomain3::vertices, _WlzThreeDViewStruct::view_mode, _WlzValues::vox, _WlzPlaneDomain::voxel_size, _WlzThreeDViewStruct::voxelRescaleFlg, _WlzThreeDViewStruct::voxelSize, _WlzTiledValues::vRank, _WlzDomain::vs3d, _WlzLVertex2::vtX, _WlzIVertex2::vtX, _WlzFVertex2::vtX, _WlzDVertex2::vtX, _WlzIVertex3::vtX, _WlzDVertex3::vtX, _WlzPolygonDomain::vtx, _WlzConvHullDomain2::vtxType, _WlzConvHullDomain3::vtxType, _WlzLVertex2::vtY, _WlzIVertex2::vtY, _WlzFVertex2::vtY, _WlzDVertex2::vtY, _WlzIVertex3::vtY, _WlzDVertex3::vtY, _WlzIndexedValues::vType, _WlzLUTValues::vType, _WlzPointValues::vType, _WlzIVertex3::vtZ, _WlzDVertex3::vtZ, _WlzRagRValues::width, _WlzRectValues::width, _WlzIntervalValues::width, WLZ_2D_DOMAINOBJ, WLZ_2D_POLYGON, WLZ_3D_DOMAINOBJ, WLZ_3D_POLYGON, WLZ_3D_VIEW_STRUCT, WLZ_3D_WARP_TRANS, WLZ_AFFINE_TRANS, WLZ_BOUNDLIST, WLZ_BOUNDLIST_HOLE, WLZ_BOUNDLIST_PIECE, WLZ_CMESH_2D, WLZ_CMESH_2D5, WLZ_CMESH_3D, WLZ_COMPOUND_ARR_1, WLZ_COMPOUND_ARR_2, WLZ_COMPOUND_LIST_1, WLZ_COMPOUND_LIST_2, WLZ_CONTOUR, WLZ_CONV_HULL, WLZ_CONVHULL_DOMAIN_2D, WLZ_CONVHULL_DOMAIN_3D, WLZ_CONVOLVE_FLOAT, WLZ_CONVOLVE_INT, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_GREY_TYPE, WLZ_ERR_MEM_ALLOC, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_TRANSFORM_TYPE, WLZ_ERR_VALUES_DATA, WLZ_ERR_VALUES_NULL, WLZ_ERR_VALUES_TYPE, WLZ_FMATCHOBJ, WLZ_GMELM_SHELL_G2D, WLZ_GMELM_SHELL_G2I, WLZ_GMELM_SHELL_G3D, WLZ_GMELM_SHELL_G3I, WLZ_GMMOD_2D, WLZ_GMMOD_2I, WLZ_GMMOD_2N, WLZ_GMMOD_3D, WLZ_GMMOD_3I, WLZ_GMMOD_3N, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_LONG, WLZ_GREY_RGBA, WLZ_GREY_SHORT, WLZ_GREY_TAB_INTL, WLZ_GREY_TAB_RAGR, WLZ_GREY_TAB_RECT, WLZ_GREY_TAB_TILED, WLZ_GREY_UBYTE, WLZ_HISTOGRAM, WLZ_INDEXED_VALUES, WLZ_INTERVALDOMAIN_INTVL, WLZ_LUT, WLZ_MESH_TRANS, WLZ_POINT_VALUES, WLZ_POINTS, WLZ_POINTS_2D, WLZ_POINTS_2I, WLZ_POINTS_3D, WLZ_POINTS_3I, WLZ_POLYGON_DOUBLE, WLZ_POLYGON_FLOAT, WLZ_POLYGON_INT, WLZ_PROPERTY_EMAP, WLZ_PROPERTY_GREY, WLZ_PROPERTY_NAME, WLZ_PROPERTY_OBJ, WLZ_PROPERTY_SIMPLE, WLZ_PROPERTY_TEXT, WLZ_RECTANGLE, WLZ_RGBA_ALPHA_GET, WLZ_RGBA_BLUE_GET, WLZ_RGBA_GREEN_GET, WLZ_RGBA_RED_GET, WLZ_TEXT, WLZ_TRANS_OBJ, WLZ_VALUE_ATTACH_ELM, WLZ_VALUE_ATTACH_NOD, WLZ_VERTEX_D2, WLZ_VERTEX_D3, WLZ_VERTEX_F2, WLZ_VERTEX_I2, WLZ_VERTEX_I3, WLZ_VERTEX_L2, WLZ_WARP_TRANS, WlzAffineTransformDimension(), WlzFreeObj(), WlzGreyTableIsTiled(), WlzGreyTableTypeToGreyType(), WlzGreyTableTypeToTableType(), WlzIndexedValueGet(), WlzIntervalCount(), WlzMakeMain(), WlzPointValueGet(), WlzStringFromEMAPPropertyType(), WlzStringFromGMModelType(), WlzStringFromGreyType(), WlzStringFromObjDomainType(), WlzStringFromObjType(), WlzStringFromObjTypeValue(), WlzStringFromObjValuesType(), WlzStringFromPropertyType(), WlzStringFromTransformType(), WlzStringFromValueAttachType(), WlzStringFromVertexType(), _WlzValues::x, _WlzIBox2::xMax, _WlzDBox2::xMax, _WlzIBox3::xMax, _WlzDBox3::xMax, _WlzIBox2::xMin, _WlzDBox2::xMin, _WlzIBox3::xMin, _WlzDBox3::xMin, _WlzIBox2::yMax, _WlzDBox2::yMax, _WlzIBox3::yMax, _WlzDBox3::yMax, _WlzIBox2::yMin, _WlzDBox2::yMin, _WlzIBox3::yMin, _WlzDBox3::yMin, _WlzThreeDViewStruct::zeta, _WlzIBox3::zMax, _WlzDBox3::zMax, _WlzIBox3::zMin, and _WlzDBox3::zMin.
Referenced by WlzPatchFacts().
const char* WlzVersion ()
Returns the current version of Woolz.
Returns
Woolz version string.
Referenced by main(), and WlzImageBlendObjToBufRGBA().