Woolz Image Processing: WlzDomainUtils
WlzDomainUtils
Files
file WlzHasIntersect.c
Determines whether two objects have an intersection.
Functions
int WlzHasIntersection (WlzObject *obj1, WlzObject *obj2, WlzErrorNum *dstErr)
Determine if two domain objects intersect. The objects must WLZ_2D_DOMAINOBJ, WLZ_3D_DOMAINOBJ or WLZ_EMPTY_OBJ. If neither object is empty then they must be of the same type.
Detailed Description
Function Documentation
int WlzHasIntersection (WlzObject * obj1, WlzObject * obj2, WlzErrorNum * dstErr)
Determine if two domain objects intersect. The objects must WLZ_2D_DOMAINOBJ, WLZ_3D_DOMAINOBJ or WLZ_EMPTY_OBJ. If neither object is empty then they must be of the same type.
Returns
non-zero if the input objects intersect
Parameters
obj1 input object 1
obj2 input object 2
dstErr error return
Source:
WlzHasIntersect.c
References _WlzValues::core, _WlzDomain::core, _WlzObject::domain, _WlzPlaneDomain::domains, _WlzDomain::i, _WlzIntervalWSpace::intdmn, _WlzIntervalWSpace::intvln, _WlzIntervalDomain::kol1, _WlzIntervalDomain::lastkl, _WlzIntervalDomain::lastln, _WlzPlaneDomain::lastpl, _WlzIntervalDomain::line1, _WlzIntervalWSpace::linpos, _WlzDomain::p, _WlzPlaneDomain::plane1, _WlzObject::type, _WlzIntervalDomain::type, WLZ_2D_DOMAINOBJ, WLZ_3D_DOMAINOBJ, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_EOO, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_INTERVALDOMAIN_RECT, WLZ_MAX, WLZ_MIN, WLZ_RASTERDIR_ILIC, WlzFreeObj(), WlzInitRasterScan(), WlzIsEmpty(), WlzMakeMain(), and WlzNextInterval().
Referenced by WlzDomainFill3D(), and WlzLabel3D().