Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzClipObjToBox.c File Reference
WlzClipObjToBox.c File Reference
WlzDomainOps
Functions for clipping the domain of either 2D or 3D domain objects so that they lie within the given axis aligned biunding box.
Functions
WlzObject * WlzClipObjToBox2D (WlzObject *srcObj, WlzIBox2 clipBox, WlzErrorNum *dstErrNum)
Clips the given object's domain so that it does not lie outside the given 2D axis aliagned clip box. Only 2D domain objects and empty objects may be clipped by this function.
WlzObject * WlzClipObjToBox3D (WlzObject *srcObj, WlzIBox3 clipBox, WlzErrorNum *dstErrNum)
Clips the given object's domain so that it does not lie outside the given 3D axis alaigned clip box.
Detailed Description
Functions for clipping the domain of either 2D or 3D domain objects so that they lie within the given axis aligned biunding box.
Author
Bill Hill
Date
March 1999
Version
Id
f3acb57bc0a4e516781c3181992f8ed82e1020f4
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzClipObjToBox2D()
WlzObject* WlzClipObjToBox2D (WlzObject * srcObj, WlzIBox2 clipBox, WlzErrorNum * dstErrNum)
Clips the given object's domain so that it does not lie outside the given 2D axis aliagned clip box. Only 2D domain objects and empty objects may be clipped by this function.
Returns
New object with clipped domain or NULL on error.
Parameters
srcObj Given source object.
clipBox Clip box.
dstErrNum Destination pointer for error, may be NULL.
References AlcFreeStackPush(), AlcMalloc(), _WlzDomain::core, _WlzObject::domain, _WlzIntervalDomain::freeptr, _WlzDomain::i, _WlzInterval::ileft, _WlzIntervalDomain::intvlines, _WlzIntervalLine::intvs, _WlzInterval::iright, _WlzIntervalDomain::kol1, _WlzIntervalDomain::lastkl, _WlzIntervalDomain::lastln, _WlzIntervalDomain::line1, _WlzIntervalLine::nintvs, _WlzObject::type, _WlzCoreDomain::type, _WlzObject::values, WLZ_2D_DOMAINOBJ, WLZ_DBG, WLZ_DBG_LVL_1, WLZ_DBG_LVL_2, WLZ_DBG_LVL_FN, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_INTERVALDOMAIN_INTVL, WLZ_INTERVALDOMAIN_RECT, WLZ_MAX, WLZ_MIN, WlzFreeObj(), WlzMakeEmpty(), WlzMakeInterval(), WlzMakeIntervalDomain(), WlzMakeMain(), _WlzIBox2::xMax, _WlzIBox2::xMin, _WlzIBox2::yMax, and _WlzIBox2::yMin.
Referenced by WlzClipObjToBox3D(), and WlzSplitMontageObj().