Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzSobel.c File Reference
WlzSobel.c File Reference
Implements a Sobel edge detection filter.
Functions
WlzObject * WlzSobel (WlzObject *srcObj, int hFlag, int vFlag, WlzErrorNum *dstErr)
Applies a Sobel edge detection filter to the given woolz object.
Detailed Description
Implements a Sobel edge detection filter.
Author
Bill Hill
Date
March 1999
Version
Id
eb7e75fdde303c26724dd4b520d1254979b50504
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzObject* WlzSobel (WlzObject * srcObj, int hFlag, int vFlag, WlzErrorNum * dstErr)
Applies a Sobel edge detection filter to the given woolz object.
Returns
Sobel filtered object.
Parameters
srcObj Given source object.
hFlag Apply horizontal edge kernel if non-zero.
vFlag Apply vertical edge kernel if non-zero.
dstErr Destination error pointer, may be NULL.
References _WlzValues::core, _WlzDomain::core, _WlzConvolution::cv, _WlzConvolution::divscale, _WlzObject::domain, _WlzConvolution::linkcount, _WlzConvolution::modflag, _WlzConvolution::offset, _WlzObject::type, _WlzCoreValues::type, _WlzConvolution::type, _WlzObject::values, WLZ_2D_DOMAINOBJ, WLZ_BO_ADD, WLZ_CONVOLVE_FLOAT, WLZ_CONVOLVE_INT, WLZ_DBG, WLZ_DBG_LVL_1, WLZ_DBG_LVL_FN, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_GREY_DATA, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_VALUES_NULL, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_RGBA, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WlzAssignObject(), WlzConvertPix(), WlzConvolveObj(), WlzFreeObj(), WlzGreyTableTypeToGreyType(), WlzImageArithmetic(), _WlzConvolution::xsize, and _WlzConvolution::ysize.