Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzPolarSample.c File Reference
WlzPolarSample.c File Reference
A rectangular to polar image resampling filter.
Functions
WlzObject * WlzPolarSample (WlzObject *srcObj, WlzIVertex2 org, double angleInc, double distInc, int nLines, int outFlag, WlzErrorNum *wlzErr)
Polar resamples the given woolz object using the given angle and radial distance increments. All angles are in radians. Notes: The linkcount of the returned object is zero.
Detailed Description
A rectangular to polar image resampling filter.
Author
Bill Hill
Date
March 1999
Version
Id
6c78a1d15efaab369b8730a8fe538d219ba41b7d
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzObject* WlzPolarSample (WlzObject * srcObj, WlzIVertex2 org, double angleInc, double distInc, int nLines, int outFlag, WlzErrorNum * wlzErr)
Polar resamples the given woolz object using the given angle and radial distance increments. All angles are in radians. Notes: The linkcount of the returned object is zero.
Returns
New polar sampled woolz object.
Parameters
srcObj Given Woolz object.
org Origin in given object about which to polar resample.
angleInc Angle increment (radians).
distInc Radial distance increment.
nLines Number of lines (angular samples).
outFlag If non zero then the outer bounding circle of the given object is used, else the inner bound is used for resampling.
wlzErr Destination error pointer, may be NULL.
References AlcFree(), AlcFreeStackPush(), AlcMalloc(), _WlzValues::core, _WlzDomain::core, _WlzGreyP::dbp, _WlzObject::domain, _WlzGreyP::flp, _WlzRectValues::freeptr, _WlzGreyValueWSpace::gVal, _WlzDomain::i, _WlzGreyP::inp, _WlzIntervalDomain::kol1, _WlzIntervalDomain::lastkl, _WlzIntervalDomain::lastln, _WlzIntervalDomain::line1, _WlzValues::r, _WlzGreyP::rgbp, _WlzGreyP::shp, _WlzObject::type, _WlzCoreDomain::type, _WlzCoreValues::type, _WlzGreyP::ubp, _WlzObject::values, _WlzIVertex2::vtX, _WlzIVertex2::vtY, WLZ_2D_DOMAINOBJ, WLZ_DBG, WLZ_DBG_LVL_1, WLZ_DBG_LVL_2, WLZ_DBG_LVL_FN, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_MEM_ALLOC, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_PARAM_DATA, WLZ_ERR_VALUES_NULL, WLZ_ERR_VALUES_TYPE, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_RGBA, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WLZ_INTERVALDOMAIN_INTVL, WLZ_INTERVALDOMAIN_RECT, WLZ_NINT, WlzFreeObj(), WlzGetBackground(), WlzGreyTableTypeToGreyType(), WlzGreyValueFreeWSp(), WlzGreyValueGet(), WlzGreyValueMakeWSp(), WlzMakeEmpty(), WlzMakeRect(), _WlzIBox2::xMax, _WlzIBox2::xMin, _WlzIBox2::yMax, and _WlzIBox2::yMin.
Referenced by WlzRegCCorObjs().