Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzSkeleton.c File Reference
WlzSkeleton.c File Reference
WlzDomainOps
Performs a proper interval-domain skeletonisation Hilditch's method.
Data Structures
struct _WlzSkIntvLn
struct _WlzExtIntv
Typedefs
typedef struct _WlzSkIntvLn WlzSkIntvLn
typedef struct _WlzExtIntv WlzExtIntv
Functions
static WlzErrorNum WlzSkStrip4 (WlzObject *, WlzObject *, WlzObject *, WlzInterval *, int, int *, int)
static WlzObject * WlzSkeleton3D (WlzObject *, int, WlzConnectType, WlzErrorNum *)
WlzObject * WlzSkeleton (WlzObject *srcObj, int smoothpasses, WlzConnectType minCon, WlzErrorNum *dstErr)
Computes the skeleton of the given object using Hilditch's method. See detail.
Detailed Description
Performs a proper interval-domain skeletonisation Hilditch's method.
Author
Jim Piper, Bill Hill, Richard Baldock
Date
March 1997
Version
Id
02ace10abd97a78f8fb58dc85e7f939801715ac2
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Typedef Documentation
typedef struct _WlzSkIntvLn WlzSkIntvLn
typedef struct _WlzExtIntv WlzExtIntv
Function Documentation
static WlzErrorNum WlzSkStrip4 (WlzObject * skObj, WlzObject * potDelObj, WlzObject * delObj, WlzInterval * delItvBase, int itvSpace, int * delArea, int smPass)
References _WlzObject::domain, _WlzDomain::i, _WlzSkIntvLn::ijleft, _WlzSkIntvLn::ijntpos, _WlzSkIntvLn::ijright, _WlzInterval::ileft, _WlzSkIntvLn::intcount, _WlzSkIntvLn::intp, _WlzIntervalWSpace::intrmn, _WlzIntervalDomain::intvlines, _WlzIntervalLine::intvs, _WlzInterval::iright, _WlzIntervalDomain::kol1, _WlzIntervalDomain::lastln, _WlzIntervalWSpace::lftpos, _WlzIntervalDomain::line1, _WlzIntervalWSpace::linpos, _WlzIntervalLine::nintvs, _WlzIntervalWSpace::nwlpos, _WlzSkIntvLn::prevright, _WlzIntervalWSpace::rgtpos, WLZ_ERR_DOMAIN_DATA, WLZ_ERR_EOO, WLZ_ERR_NONE, WLZ_MIN, WLZ_RASTERDIR_ILIC, WlzInitRasterScan(), WlzMakeInterval(), and WlzNextInterval().
Referenced by WlzSkeleton3D().
static WlzObject * WlzSkeleton3D (WlzObject * srcObj, int smoothpasses, WlzConnectType minCon, WlzErrorNum * dstErr)
References ALC_ER_NONE, AlcFreeStackPush(), AlcMalloc(), _WlzValues::core, _WlzDomain::core, _WlzObject::domain, _WlzIntervalDomain::freeptr, _WlzDomain::i, _WlzIntervalDomain::kol1, _WlzIntervalDomain::lastkl, _WlzIntervalDomain::lastln, _WlzIntervalDomain::line1, _WlzCoreDomain::type, WLZ_18_CONNECTED, WLZ_26_CONNECTED, WLZ_2D_DOMAINOBJ, WLZ_4_CONNECTED, WLZ_6_CONNECTED, WLZ_8_CONNECTED, WLZ_ERR_DOMAIN_DATA, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_MEM_ALLOC, WLZ_ERR_NONE, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_PARAM_DATA, WLZ_INTERVALDOMAIN_INTVL, WLZ_INTERVALDOMAIN_RECT, WlzAssignDomain(), WlzDiffDomain(), WlzFreeDomain(), WlzFreeObj(), WlzIntervalCount(), WlzMakeIntervalDomain(), WlzMakeMain(), WlzNewIDomain(), and WlzSkStrip4().
Referenced by WlzSkeleton().