Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzCompDispIncGrey.c File Reference
WlzCompDispIncGrey.c File Reference
Functions to compute vector displacement maps from two warps of domain objects which originate from a common object with incrementing integer grey values.
Functions
WlzCompoundArray * WlzCompDispIncGrey (WlzObject *obj0, WlzObject *obj1, WlzErrorNum *dstErr)
Computes a compound array object which will have either two or three members that are the elements of the computed displacement vector field. This contains the displacements from the first to the second object. The two objects must have been derived from the same domain object with integer incrementing grey values, see WlzGreySetIncValues().
Detailed Description
Functions to compute vector displacement maps from two warps of domain objects which originate from a common object with incrementing integer grey values.
Author
Bill Hill
Date
November 2009
Version
Id
735a7b9a8d41eb36415dc67a634e47c2ce99bcb6
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzCompoundArray* WlzCompDispIncGrey (WlzObject * obj0, WlzObject * obj1, WlzErrorNum * dstErr)
Computes a compound array object which will have either two or three members that are the elements of the computed displacement vector field. This contains the displacements from the first to the second object. The two objects must have been derived from the same domain object with integer incrementing grey values, see WlzGreySetIncValues().
Returns
Compound array with integer displacement values in x, y, z order.
Parameters
obj0 First object.
obj1 Second object.
dstErr Destination error pointer, may be NULL.
References AlcFree(), AlcMalloc(), AlgSort(), _WlzIntervalWSpace::colpos, _WlzValues::core, _WlzDomain::core, _WlzObject::domain, _WlzPlaneDomain::domains, _WlzGreyP::inp, _WlzGreyV::inv, _WlzIntervalWSpace::lftpos, _WlzIntervalWSpace::linpos, _WlzDomain::p, _WlzPlaneDomain::plane1, _WlzIntervalWSpace::rgtpos, _WlzPixelV::type, _WlzObject::type, _WlzCoreDomain::type, _WlzCoreValues::type, _WlzGreyWSpace::u_grintptr, _WlzPixelV::v, _WlzObject::values, _WlzVoxelValues::values, _WlzValues::vox, WLZ_2D_DOMAINOBJ, WLZ_3D_DOMAINOBJ, WLZ_COMPOUND_ARR_1, WLZ_ERR_DOMAIN_DATA, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_EOO, WLZ_ERR_MEM_ALLOC, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_UNIMPLEMENTED, WLZ_ERR_VALUES_NULL, WLZ_ERR_VALUES_TYPE, WLZ_GREY_INT, WLZ_GREY_TAB_RAGR, WlzFreeObj(), WlzGreyTableIsTiled(), WlzGreyValueTableType(), WlzInitGreyScan(), WlzMakeCompoundArray(), WlzMakeMain(), WlzNewValuesVox(), WlzNextGreyInterval(), and WlzVolume().