Woolz Image Processing: _AlcHashTable Struct Reference
_AlcHashTable Struct Reference
AlcHashTable
A hash table. Typedef: AlcHashTable.
Data Fields
int(* keyCmp)(void *, void *)
size_t(* hashFn)(void *)
size_t tableSz
AlcHashItem ** table
Detailed Description
A hash table. Typedef: AlcHashTable.
Field Documentation
int(* _AlcHashTable::keyCmp) (void *, void *)
Key comparison function
Referenced by AlcHashItemGet(), AlcHashItemInsert(), and AlcHashTableNew().
size_t(* _AlcHashTable::hashFn) (void *)
The hashing function
Referenced by AlcHashItemGet(), AlcHashItemInsert(), AlcHashItemOrder(), AlcHashItemUnlink(), AlcHashTableEntryInsert(), and AlcHashTableNew().
size_t _AlcHashTable::tableSz
Number of list slots in the hash table
Referenced by AlcHashItemGet(), AlcHashItemInsert(), AlcHashItemOrder(), AlcHashItemUnlink(), AlcHashTableCount(), AlcHashTableFree(), AlcHashTableIterate(), and AlcHashTableNew().
AlcHashItem** _AlcHashTable::table
Table of lists
Referenced by AlcHashItemGet(), AlcHashItemInsert(), AlcHashItemUnlink(), AlcHashTableCount(), AlcHashTableFree(), AlcHashTableIterate(), AlcHashTableNew(), and AlcHashTableUnlinkAll().
The documentation for this struct was generated from the following file:
/export/data0/bill/MouseAtlas/Build/src/Woolz/libAlc/AlcType.h