Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/binWlz/tst.c File Reference
tst.c File Reference
Functions
void ThrowIfError (const char *funcName, WlzErrorNum err)
int main (int argc, char **argv)
Function Documentation
void ThrowIfError (const char * funcName, WlzErrorNum err)
References WLZ_ERR_NONE.
Referenced by main().
int main (int argc, char ** argv)
References _WlzPolygonDomain::nvertices, ThrowIfError(), _WlzFVertex2::vtX, _WlzPolygonDomain::vtx, _WlzFVertex2::vtY, WLZ_ERR_NONE, WLZ_POLYGON_FLOAT, WLZ_SIMPLE_FILL, WlzArea(), WlzMakePolygonDomain(), WlzObjectFacts(), WlzPolyToObj(), _WlzIBox2::xMax, _WlzIBox2::xMin, _WlzIBox2::yMax, and _WlzIBox2::yMin.
Referenced by AlcCPQItemUnlink(), AlcHeapTop(), AlcKDTGetNN(), AlcUFTreeUnion(), WlzCannyDeriche(), WlzDistMetricDirVertex3D(), WlzGeomLineSegmentsIntersect(), WlzImageBlendObjToBufRGBA(), WlzLBTTestOutputNodesVtk(), WlzNMSuppress(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzRsvFilterBuffer(), WlzToArray1D(), and WlzVerticesBuildTree().