Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzAssign.c File Reference
WlzAssign.c File Reference
WlzAllocation
Woolz objects domains and values maintain a linkcount, which records it's usage by other objects, domains or values. To increment a linkcount the appropriate assignment function should be used.
Functions
WlzObject * WlzAssignObject (WlzObject *obj, WlzErrorNum *dstErr)
Assign an object (increment it's linkcount) by first checking for NULL, then the value of linkcount, before incrementing the linkcount. If used concientiously, assignment should avoid memory errors.
WlzDomain WlzAssignDomain (WlzDomain domain, WlzErrorNum *dstErr)
Assign a domain by incrementing it's linkcount.
WlzValues WlzAssignValues (WlzValues values, WlzErrorNum *dstErr)
Assign a values by incrementing it's linkcount.
WlzProperty WlzAssignProperty (WlzProperty property, WlzErrorNum *dstErr)
Assign a property by incrementing it's linkcount.
WlzPropertyList * WlzAssignPropertyList (WlzPropertyList *pList, WlzErrorNum *dstErr)
Assigned a Woolz property list, incrementing the link count or the number of times the property list is used.
WlzAffineTransform * WlzAssignAffineTransform (WlzAffineTransform *trans, WlzErrorNum *dstErr)
Assign an affine transform by incrementing it's linkcount.
WlzTransform WlzAssignTransform (WlzTransform t, WlzErrorNum *dstErr)
Assign a transform by incrementing it's linkcount.
WlzThreeDViewStruct * WlzAssign3DViewStruct (WlzThreeDViewStruct *viewStr, WlzErrorNum *dstErr)
Assign an woolz 3D view structure by incrementing it's linkcount.
WlzBoundList * WlzAssignBoundList (WlzBoundList *blist, WlzErrorNum *dstErr)
Assign a boundary list by incrementing it's linkcount.
WlzPolygonDomain * WlzAssignPolygonDomain (WlzPolygonDomain *poly, WlzErrorNum *dstErr)
Assign a polygon domain by incrementing it's linkcount.
WlzGMModel * WlzAssignGMModel (WlzGMModel *model, WlzErrorNum *dstErr)
Assign a geometric model by incrementing it's linkcount.
int WlzUnlink (int *linkcount, WlzErrorNum *dstErr)
Unlink an object, domain or values by decrementing and testing it's linkcount.
Detailed Description
Woolz objects domains and values maintain a linkcount, which records it's usage by other objects, domains or values. To increment a linkcount the appropriate assignment function should be used.
Author
Bill Hill, Richard Baldock, Christophe Dubreuil
Date
March 1999
Version
Id
64c1d30c49f948b3f981c4da288b90fd8140c05a
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzPropertyList* WlzAssignPropertyList (WlzPropertyList * pList, WlzErrorNum * dstErr)
Assigned a Woolz property list, incrementing the link count or the number of times the property list is used.
Returns
Property list with incremented link count or NULL on error.
Parameters
pList Given property list.
dstErr Destination error pointer, may be NULL.
References _WlzPropertyList::linkcount, WLZ_ERR_LINKCOUNT_DATA, WLZ_ERR_NONE, and WLZ_ERR_PROPERTY_NULL.
Referenced by WlzDGTensorPDFeature(), WlzDGTensorSDFeature(), WlzEffReadObjNifti(), WlzEffWriteObjNrrd(), WlzMakeMain(), WlzNObjGreyStats(), and WlzReadObj().