Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzCMeshSMReg.c File Reference
WlzCMeshSMReg.c File Reference
Data Structures
struct _WlzSMNod3
Typedefs
typedef struct _WlzSMNod3 WlzSMNod3
Enumerations
enum _WlzSMNodFlg3 {
WLZ_SMNOD_FLG_NONE = (0),
WLZ_SMNOD_FLG_VALID = (1),
WLZ_SMNOD_FLG_FREE = (1 << 1)
}
Functions
WlzObject WlzCMeshTrRegSM3D (WlzObject *sObj, int nFixN, WlzDVertex3 *gNod, int nFixD, WlzDVertex3 *gDsp, WlzErrorNum *dstErr)
Typedef Documentation
WlzSMNod3
typedef struct _WlzSMNod3 WlzSMNod3
Enumeration Type Documentation
_WlzSMNodFlg3
enum _WlzSMNodFlg3
Enumerator
WLZ_SMNOD_FLG_NONE
WLZ_SMNOD_FLG_VALID
WLZ_SMNOD_FLG_FREE
Function Documentation
WlzCMeshTrRegSM3D()
WlzObject WlzCMeshTrRegSM3D (WlzObject * sObj, int nFixN, WlzDVertex3 * gNod, int nFixD, WlzDVertex3 * gDsp, WlzErrorNum * dstErr)
References AlcCalloc(), AlcFree(), AlcVectorItemGet(), _WlzDomain::cm3, _WlzDomain::core, _WlzObject::domain, _WlzSMNod3::dsp, _WlzCMeshRes::elm, _WlzCMeshNod3D::idx, _WlzCMeshElm3D::idx, _WlzCMeshEntRes::maxEnt, _WlzSMNod3::nbr, _WlzSMNod3::nNbr, _WlzSMNod3::nod, _WlzCMeshRes::nod, _WlzSMNod3::pos, _WlzCMeshNod3D::pos, _WlzCMesh3D::res, _WlzObject::type, _WlzCMeshEntRes::vec, _WlzDVertex3::vtX, _WlzDVertex3::vtY, _WlzDVertex3::vtZ, WLZ_CMESH_3D, WLZ_CMESH_ELM3D_GET_NODE_0, WLZ_CMESH_ELM3D_GET_NODE_1, WLZ_CMESH_ELM3D_GET_NODE_2, WLZ_CMESH_ELM3D_GET_NODE_3, WLZ_ERR_DOMAIN_DATA, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_DOUBLE_DATA, WLZ_ERR_MEM_ALLOC, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_PARAM_DATA, WLZ_MESH_TOLERANCE, WLZ_SMNOD_FLG_FREE, WLZ_SMNOD_FLG_VALID, WLZ_VTX_3_EQUAL, WlzCMeshElmEnclosingPos3D(), and WlzCMeshNodRingNodIndices3D().