Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlzExtFF/WlzExtFFBibUtils.c File Reference
WlzExtFFBibUtils.c File Reference
libWlzExt
Woolz IO bibfile utility functions to write and parse records written in bibfile format.
Functions
WlzThreeDViewStruct * WlzEffBibRead3DView (FILE *fP, char **dstMsg, WlzErrorNum *dstErr)
Reads a 3D view from the given file pointer.
WlzErrorNum WlzEffBibWrite3DSectionViewParamsRecord (FILE *fp, char *recordName, WlzThreeDViewStruct *wlzViewStr)
Write the section view parameters in the bibtex style record using the bibFile library.
WlzErrorNum WlzEffBibParse3DSectionViewParamsRecord (BibFileRecord *bibfileRecord, WlzThreeDViewStruct *wlzViewStr)
Parse the bibfile record for a woolz 3D view structure setting paramters in the given view structure.
WlzErrorNum WlzEffBibWriteWarpTransformParamsRecord (FILE *fp, char *recordName, WlzFnType basisFnType, WlzTransformType affineType, WlzMeshGenMethod meshMthd, int meshMinDst, int meshMaxDst)
Write the details of a warp transformation parameters. Note this does not write the warp transformation itself.
WlzErrorNum WlzEffBibParseWarpTransformParamsRecord (BibFileRecord *bibfileRecord, WlzFnType *basisFnType, WlzTransformType *affineType, WlzMeshGenMethod *meshMthd, int *meshMinDst, int *meshMaxDst)
Parse the bibfile record for the warp transformation parameter settings.
WlzErrorNum WlzEffBibWriteTiePointVtxsRecord (FILE *fp, char *recordName, int index, WlzDVertex3 dstVtx, WlzDVertex3 srcVtx, int relativeFlg)
Write a tie-point record in bibtex style.
WlzErrorNum WlzEffBibParseTiePointVtxsRecord (BibFileRecord *bibfileRecord, int *index, WlzDVertex3 *dstVtx, WlzDVertex3 *srcVtx, int *relativeFlg)
Parse the bibfile record for a tie-point pair of vertices. The record should also include an index so that tie-point ordering is preserved.
WlzErrorNum WlzEffBibWriteFileRecord (FILE *fp, char *recordName, char *fileName, WlzEffFormat fileType)
Write a bibfile record to record the file name and file type.
WlzErrorNum WlzEffBibParseFileRecord (BibFileRecord *bibfileRecord, int *dstIndex, char **dstFileName, WlzEffFormat *dstFileType)
Parse a bibfile record for a filename and type.
WlzErrorNum WlzEffBibWriteWarpInputSegmentationParamsRecord (FILE *fp, char *recordName, int normFlg, int histoFlg, int shadeFlg, int gaussFlg, double width)
Write a warp segmentation parameter record i.e. the image processing operations and paramters for extracting the gene-expression domain.
WlzErrorNum WlzEffBibParseWarpInputSegmentationParamsRecord (BibFileRecord *bibfileRecord, int *normFlg, int *histoFlg, int *shadeFlg, int *gaussFlg, double *width, int *threshLow, int *threshHigh)
Parse the bibfile record for a MAPaint WarpInputSegmentationParams record.
WlzErrorNum WlzEffBibWriteWarpInputThresholdParamsRecord (FILE *fp, char *recordName, WlzEffBibWarpInputThresholdParamsStruct *paramStruct)
WlzErrorNum WlzEffBibParseWarpInputThresholdParamsRecord (BibFileRecord *bibfileRecord, WlzEffBibWarpInputThresholdParamsStruct *paramStruct)
Detailed Description
Woolz IO bibfile utility functions to write and parse records written in bibfile format.
Author
Richard Baldock
Date
January 2002
Version
Id
72ff22c35706cfec1c71229cb86c2c05ff6df2a4
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzErrorNum WlzEffBibWriteWarpInputThresholdParamsRecord (FILE * fp, char * recordName, WlzEffBibWarpInputThresholdParamsStruct * paramStruct)
References BIBFILE_ER_NONE, BibFileFieldMakeVa(), BibFileRecordFree(), BibFileRecordMake(), BibFileRecordWrite(), _WlzEffBibWarpInputThresholdParamsStruct::colorEllipseEcc, _WlzEffBibWarpInputThresholdParamsStruct::distanceThreshFlg, _WlzEffBibWarpInputThresholdParamsStruct::globalThreshFlg, _WlzEffBibWarpInputThresholdParamsStruct::globalThreshVtx, _WlzEffBibWarpInputThresholdParamsStruct::highRGBPoint, _WlzEffBibWarpInputThresholdParamsStruct::incrThreshFlg, _WlzEffBibWarpInputThresholdParamsStruct::lowRGBPoint, _WlzEffBibWarpInputThresholdParamsStruct::pickThreshFlg, _WlzGreyV::rgbv, _WlzEffBibWarpInputThresholdParamsStruct::threshColorChannel, _WlzEffBibWarpInputThresholdParamsStruct::thresholdType, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeHigh, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeLow, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeRGBHigh, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeRGBLow, _WlzEffBibWarpInputThresholdParamsStruct::threshRGBCombination, _WlzEffBibWarpInputThresholdParamsStruct::threshRGBSpace, _WlzPixelV::v, _WlzIVertex2::vtX, _WlzIVertex2::vtY, WLZ_ERR_NONE, WLZ_ERR_WRITE_INCOMPLETE, WLZ_RGBA_CHANNEL_BLUE, WLZ_RGBA_CHANNEL_BRIGHTNESS, WLZ_RGBA_CHANNEL_CYAN, WLZ_RGBA_CHANNEL_GREEN, WLZ_RGBA_CHANNEL_GREY, WLZ_RGBA_CHANNEL_HUE, WLZ_RGBA_CHANNEL_MAGENTA, WLZ_RGBA_CHANNEL_RED, WLZ_RGBA_CHANNEL_SATURATION, WLZ_RGBA_CHANNEL_YELLOW, WLZ_RGBA_SPACE_CMY, WLZ_RGBA_SPACE_GREY, WLZ_RGBA_SPACE_HSB, WLZ_RGBA_SPACE_RGB, WLZ_RGBA_THRESH_BOX, WLZ_RGBA_THRESH_MULTI, WLZ_RGBA_THRESH_NONE, WLZ_RGBA_THRESH_PLANE, WLZ_RGBA_THRESH_SINGLE, WLZ_RGBA_THRESH_SLICE, WLZ_RGBA_THRESH_SPHERE, and WlzValueMatchString().
WlzErrorNum WlzEffBibParseWarpInputThresholdParamsRecord (BibFileRecord * bibfileRecord, WlzEffBibWarpInputThresholdParamsStruct * paramStruct)
References BibFileFieldParseFmt(), _WlzEffBibWarpInputThresholdParamsStruct::colorEllipseEcc, _WlzEffBibWarpInputThresholdParamsStruct::distanceThreshFlg, BibFileRecord::field, _WlzEffBibWarpInputThresholdParamsStruct::globalThreshFlg, _WlzEffBibWarpInputThresholdParamsStruct::globalThreshVtx, _WlzEffBibWarpInputThresholdParamsStruct::highRGBPoint, _WlzEffBibWarpInputThresholdParamsStruct::incrThreshFlg, _WlzEffBibWarpInputThresholdParamsStruct::lowRGBPoint, _BibFileField::name, _BibFileField::next, _WlzEffBibWarpInputThresholdParamsStruct::pickThreshFlg, _WlzGreyV::rgbv, _WlzEffBibWarpInputThresholdParamsStruct::threshColorChannel, _WlzEffBibWarpInputThresholdParamsStruct::thresholdType, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeHigh, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeLow, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeRGBHigh, _WlzEffBibWarpInputThresholdParamsStruct::threshRangeRGBLow, _WlzEffBibWarpInputThresholdParamsStruct::threshRGBCombination, _WlzEffBibWarpInputThresholdParamsStruct::threshRGBSpace, _WlzPixelV::v, _BibFileField::value, _WlzIVertex2::vtX, _WlzIVertex2::vtY, WLZ_ERR_NONE, WLZ_ERR_PARAM_NULL, WLZ_ERR_READ_INCOMPLETE, WLZ_RGBA_CHANNEL_BLUE, WLZ_RGBA_CHANNEL_BRIGHTNESS, WLZ_RGBA_CHANNEL_CYAN, WLZ_RGBA_CHANNEL_GREEN, WLZ_RGBA_CHANNEL_GREY, WLZ_RGBA_CHANNEL_HUE, WLZ_RGBA_CHANNEL_MAGENTA, WLZ_RGBA_CHANNEL_RED, WLZ_RGBA_CHANNEL_SATURATION, WLZ_RGBA_CHANNEL_YELLOW, WLZ_RGBA_SPACE_CMY, WLZ_RGBA_SPACE_GREY, WLZ_RGBA_SPACE_HSB, WLZ_RGBA_SPACE_RGB, WLZ_RGBA_THRESH_BOX, WLZ_RGBA_THRESH_MULTI, WLZ_RGBA_THRESH_NONE, WLZ_RGBA_THRESH_PLANE, WLZ_RGBA_THRESH_SINGLE, WLZ_RGBA_THRESH_SLICE, WLZ_RGBA_THRESH_SPHERE, and WlzStringMatchValue().