Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlzExtFF/WlzExtFFTxt.c File Reference
WlzExtFFTxt.c File Reference
libWlzExt
Functions for writing Woolz objects to a simple text '.txt' data format.
Functions
WlzErrorNum WlzEffWriteObjTxt (FILE *fP, WlzObject *obj, char *params)
Detailed Description
Functions for writing Woolz objects to a simple text '.txt' data format.
Author
Richard Baldock
Date
April 2010
Version
Id
4a2208fe04c91473c5f194c2c95504c78607b3a1
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Todo:
Bug:
None known.
Function Documentation
WlzErrorNum WlzEffWriteObjTxt (FILE * fP, WlzObject * obj, char * params)
References _WlzValues::core, _WlzDomain::core, _WlzObject::domain, _WlzDomain::i, _WlzGreyP::inp, _WlzIntervalDomain::kol1, _WlzIntervalDomain::lastkl, _WlzIntervalDomain::lastln, _WlzIntervalDomain::line1, _WlzValues::obj, _WlzValues::r, _WlzGreyP::shp, _WlzObject::type, _WlzGreyP::ubp, _WlzGreyP::v, _WlzObject::values, _WlzRectValues::values, WLZ_2D_DOMAINOBJ, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_PARAM_NULL, WLZ_ERR_VALUES_NULL, WLZ_GREY_ERROR, WLZ_GREY_INT, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WLZ_TRANS_OBJ, WlzCutObjToBox2D(), WlzFreeObj(), WlzGreyTypeFromObj(), _WlzIBox2::xMax, _WlzIBox2::xMin, _WlzIBox2::yMax, and _WlzIBox2::yMin.
Referenced by WlzEffWriteObj().