Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/binWlz/WlzGetSubSectionFromObj.c File Reference
WlzGetSubSectionFromObj.c File Reference
Basic Woolz Operations
Cuts a section from an object with the domain of a given object.
Functions
int getopt (int argc, char *const *argv, const char *optstring)
int main (int argc, char *argv[])
Variables
char * optarg
int optind
int opterr
int optopt
Detailed Description
Cuts a section from an object with the domain of a given object.
Author
Bill Hill
Date
March 2009
Version
Id
a3bd9f977b32d56f0a2c6c5ab8a98e42eef752ca
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Binary
ref wlzgetsubsectionfromobj "WlzGetSubSectionFromObj"
Function Documentation
int getopt (int argc, char *const * argv, const char * optstring)
Referenced by AlcHeapTop(), main(), WlzImageBlendObjToBufRGBA(), WlzLBTTestOutputNodesVtk(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzRsvFilterBuffer(), WlzToArray1D(), and WlzVerticesBuildTree().
int main (int argc, char * argv[])
References ALG_M_PI, _WlzThreeDViewStruct::dist, _WlzThreeDViewStruct::fixed, getopt(), optarg, opterr, optind, _WlzThreeDViewStruct::phi, _WlzThreeDViewStruct::ref_obj, _WlzThreeDViewStruct::scale, _WlzThreeDViewStruct::theta, _WlzThreeDViewStruct::up, _WlzThreeDViewStruct::view_mode, _WlzDVertex3::vtX, _WlzDVertex3::vtY, _WlzDVertex3::vtZ, WLZ_3D_VIEW_STRUCT, WLZ_ERR_NONE, WLZ_ERR_WRITE_EOF, WLZ_INTERPOLATION_NEAREST, WLZ_STATUE_MODE, WLZ_UP_IS_UP_MODE, WLZ_ZETA_MODE, WlzAssignObject(), WlzFree3DViewStruct(), WlzFreeObj(), WlzGetSubSectionFromObject(), WlzInit3DViewStruct(), WlzMake3DViewStruct(), WlzReadObj(), WlzStringFromErrorNum(), WlzStringMatchValue(), WlzVersion(), WlzWriteObj(), and _WlzThreeDViewStruct::zeta.
Referenced by AlcCPQItemUnlink(), AlcHeapTop(), AlcKDTGetNN(), AlcUFTreeUnion(), WlzCannyDeriche(), WlzDistMetricDirVertex3D(), WlzGeomLineSegmentsIntersect(), WlzImageBlendObjToBufRGBA(), WlzLBTTestOutputNodesVtk(), WlzNMSuppress(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzRsvFilterBuffer(), WlzToArray1D(), and WlzVerticesBuildTree().
Variable Documentation
char* optarg
Referenced by AlcHeapTop(), main(), WlzImageBlendObjToBufRGBA(), WlzLBTTestOutputNodesVtk(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzRsvFilterBuffer(), WlzToArray1D(), and WlzVerticesBuildTree().
int optind
Referenced by AlcHeapTop(), main(), WlzImageBlendObjToBufRGBA(), WlzLBTTestOutputNodesVtk(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzToArray1D(), and WlzVerticesBuildTree().
int opterr
Referenced by AlcHeapTop(), main(), WlzImageBlendObjToBufRGBA(), WlzLBTTestOutputNodesVtk(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzRsvFilterBuffer(), WlzToArray1D(), and WlzVerticesBuildTree().
int optopt
Referenced by AlcHeapTop(), WlzImageBlendObjToBufRGBA(), WlzLBTTestOutputNodesVtk(), WlzRankFilter(), WlzRasterLineSetItv2D(), WlzToArray1D(), and WlzVerticesBuildTree().