Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzGeometryTrackUpAndDown_s.c File Reference
WlzGeometryTrackUpAndDown_s.c File Reference
WlzGeoModel
Tracks contours forming surface patches.
Macros
#define NumberToTrack (5)
#define MaxNumOfFiles (100)
#define TOL 1.0e-5
#define PYTHAG(a, b)
#define MAX(a, b)
#define SIGN(a, b) ((b) >= 0.0 ? fabs(a) : -fabs(a))
Functions
double ** matrix (int nrl, int nrh, int ncl, int nch)
double * vector (int nl, int nh)
void free_vector (double *v, int nl, int nh)
void free_matrix (double **m, int nrl, int nrh, int ncl, int nch)
void nrerror (char error_text[])
WlzDVertex3 * WlzGeometryTrackUpAndDown_s (int numberOfPixelsZ, int startTrackingFile, int numberOfFilesDownOrUp, double disForInAndOutGuid, double disForInAndOut, unsigned char **TwoDImageFilesNameList, int numOf2DWlzFiles, int downOrUp, int sectionLength_N, int subSubSectionLength_L, int numberOfSampleP_k, char *surfacePointFileName, char *surfaceInPointFileName, char *surfaceOutPointFileName, int startShell, int endShell, int startSection, int endSection, double minDis, WlzErrorNum *dstErr)
Track a curved path through a set of geometric model shells.
Detailed Description
Tracks contours forming surface patches.
Author
Jianguo Rao
Date
January 2003
Version
Id
bbeda45f47c6efa96337fa59faa956fb1ef7ed64
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Macro Definition Documentation
#define NumberToTrack (5)
Referenced by WlzGeometryTrackUpAndDown_s().
#define MaxNumOfFiles (100)
Referenced by WlzGeometryTrackUpAndDown_s().
#define TOL 1.0e-5
Referenced by WlzGeometryTrackUpAndDown_s().
#define PYTHAG (a, b)
Value:
((at=fabs(a)) > (bt=fabs(b)) ? \
(ct=bt/at,at*sqrt(1.0+ct*ct)) : (bt ? (ct=at/bt,bt*sqrt(1.0+ct*ct)): 0.0))
#define MAX (a, b)
Value:
(maxarg1=(a),maxarg2=(b),(maxarg1) > (maxarg2) ?\
        (maxarg1) : (maxarg2))
#define SIGN (a, b) ((b) >= 0.0 ? fabs(a) : -fabs(a))
Function Documentation
double ** matrix (int nrl, int nrh, int ncl, int nch)
References nrerror().
Referenced by WlzAffineTransformFromSpinSqueeze(), and WlzGeometryTrackUpAndDown_s().
double * vector (int nl, int nh)
References nrerror(), and _WlzGeomPolyListItem2D::v.
Referenced by nrerror(), and WlzGeometryTrackUpAndDown_s().
void free_vector (double * v, int nl, int nh)
Referenced by nrerror(), and WlzGeometryTrackUpAndDown_s().
void free_matrix (double ** m, int nrl, int nrh, int ncl, int nch)
Referenced by WlzGeometryTrackUpAndDown_s().
void nrerror (char error_text[])
References AlcFree(), AlcMalloc(), AlcVectorItemGet(), _WlzGMShell::child, _WlzGMModel::child, _WlzVertexP::d2, _WlzGMVertexT::diskT, _WlzGMVertex::diskT, _WlzGMLoopT::edgeT, free_vector(), _WlzGMVertex::geo, _WlzGMVertex::idx, _WlzGMDiskT::idx, _WlzGMModelR::loopT, _WlzGMVertexT::next, _WlzGMEdgeT::next, _WlzGMLoopT::next, _WlzGMShell::next, _WlzGMResource::numIdx, _WlzGMEdgeT::prev, _WlzGMModel::res, _WlzGMModel::type, _WlzGeomPolyListItem2D::v, _WlzVertexP::v, _WlzGMResource::vec, vector(), _WlzGMDiskT::vertex, _WlzGMModelR::vertex, _WlzGMDiskT::vertexT, _WlzGMEdgeT::vertexT, _WlzGMVertexGU::vg2D, _WlzGMVertexGU::vg2I, _WlzIVertex2::vtX, _WlzDVertex2::vtX, _WlzGMVertexG2I::vtx, _WlzGMVertexG2D::vtx, _WlzIVertex2::vtY, _WlzDVertex2::vtY, WLZ_ERR_DOMAIN_TYPE, WLZ_ERR_MEM_ALLOC, WLZ_ERR_NONE, WLZ_GMMOD_2D, WLZ_GMMOD_2I, WlzGMModelDeleteV(), and WlzValueCopyDVertexToDVertex().
Referenced by matrix(), and vector().