Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzImageBlend.c File Reference
WlzImageBlend.c File Reference
Functions for blending images.
Macros
#define WLZ_FAST_CODE
#define restrict
Functions
WlzErrorNum WlzImageBlendObjToBufRGBA (WlzUByte *buffer, WlzObject *obj, WlzIVertex2 bufOrg, WlzIVertex2 bufSz, WlzUInt useAlpha, WlzUInt color)
Blends the given 2D object's domain into the given buffer using Porter Duff source over destination. Object values are ignored.
Detailed Description
Functions for blending images.
Author
Bill Hill
Date
December 2016
Version
Id
bda3e08f2bfc2632220f7627778de987bdd1aa44
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2016], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Macro Definition Documentation
#define WLZ_FAST_CODE
#define restrict
Referenced by WlzImageBlendObjToBufRGBA().
Function Documentation
WlzErrorNum WlzImageBlendObjToBufRGBA (WlzUByte * buffer, WlzObject * obj, WlzIVertex2 bufOrg, WlzIVertex2 bufSz, WlzUInt useAlpha, WlzUInt color)
Blends the given 2D object's domain into the given buffer using Porter Duff source over destination. Object values are ignored.
Returns
Woolz error code.
Parameters
buffer Given buffer with either 3 or (when alpha is used) 4 bytes per pixel.
obj Given object to blend into the buffer.
bufOrg Position of the buffer origin.
bufSz Size of the buffer.
useAlpha Use alpha channel if non-zero.
color Colour to blend within the object's domain.
References Alc2Free(), getopt(), _WlzIntervalWSpace::lftpos, _WlzIntervalWSpace::linpos, main(), optarg, opterr, optind, optopt, restrict, _WlzIntervalWSpace::rgtpos, _WlzObject::type, _WlzIVertex2::vtX, _WlzIVertex2::vtY, WLZ_2D_DOMAINOBJ, WLZ_ERR_EOO, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_PROPERTY_NULL, WLZ_GREY_RGBA, WLZ_RASTERDIR_ILIC, WLZ_RGBA_ALPHA_GET, WLZ_RGBA_BLUE_GET, WLZ_RGBA_GREEN_GET, WLZ_RGBA_RED_GET, WLZ_RGBA_RGBA_SET, WlzAssignObject(), WlzBoundingBox2I(), WlzBoundingBoxUnion2I(), WlzFreeObj(), WlzFromArray2D(), WlzInitRasterScan(), WlzNextInterval(), WlzReadObj(), WlzStringFromErrorNum(), WlzToArray2D(), WlzVersion(), WlzWriteObj(), _WlzIBox2::xMax, _WlzIBox2::xMin, _WlzIBox2::yMax, and _WlzIBox2::yMin.