Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/binWlzApp/WlzInterpolateSectionViewerBibFiles.c File Reference
WlzInterpolateSectionViewerBibFiles.c File Reference
Extended Woolz Applications.
Automatically interpolates bib files.
Functions
int main (int argc, char **argv)
Detailed Description
Automatically interpolates bib files.
Author
Jianguo Rao
Date
August 2002
Version
Id
fbf4bb51a43398804112ded1b2e5834fff81f2d2
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Binary
ref wlzinterpolatesectionviewerbibfiles "WlzInterpolateSectionViewerBibFiles"
Function Documentation
int main (int argc, char ** argv)
References AlcStrDup(), BIBFILE_ER_NONE, BibFileFieldMakeVa(), BibFileRecordFree(), BibFileRecordMake(), BibFileRecordRead(), BibFileRecordWrite(), _WlzThreeDViewStruct::dist, _WlzThreeDViewStruct::fixed, getopt(), BibFileRecord::name, optarg, _WlzThreeDViewStruct::phi, _WlzThreeDViewStruct::scale, _WlzThreeDViewStruct::theta, _WlzThreeDViewStruct::type, _WlzDVertex3::vtX, _WlzDVertex3::vtY, _WlzDVertex3::vtZ, Wlz3DViewGetPlaneEqn(), WLZ_3D_VIEW_STRUCT, WLZ_ERR_NONE, WLZ_FN_BASIS_3DMQ, WLZ_MESH_GENMETHOD_GRADIENT, WLZ_TRANSFORM_2D_NOSHEAR, WLZEFF_FORMAT_WLZ, WlzEffBibParse3DSectionViewParamsRecord(), WlzEffBibWrite3DSectionViewParamsRecord(), WlzEffBibWriteFileRecord(), WlzEffBibWriteWarpTransformParamsRecord(), WlzFree3DViewStruct(), WlzFreeObj(), WlzMake3DViewStruct(), WlzReadObj(), WlzVersion(), and _WlzThreeDViewStruct::zeta.