Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/binWlzApp/WlzPatchObjRegister.c File Reference
WlzPatchObjRegister.c File Reference
Extended Woolz Applications.
Registers patch objects and outputs a single object.
Data Structures
struct _patchTree
Typedefs
typedef struct _patchTree WlzPatchTree
Functions
int WlzIsAdjacentPatch (WlzObject *obj1, WlzObject *obj2)
int sortPatch (const void *p1, const void *p2)
WlzPatchTree * WlzMakePatchTree (WlzObject *obj, int depth, double cost)
WlzErrorNum WlzGetPatchTreeToDepth (WlzObject **objs, int nobjs, WlzPatchTree *patchTree, int depth)
WlzPatchTree * WlzGetPatchTree (WlzObject *obj, WlzObject **objs, int nobjs)
WlzErrorNum WlzFreePatchTree (WlzPatchTree *patchTree)
double WlzMass (WlzObject *obj, WlzErrorNum *dstErr)
WlzObject * WlzGreyShift (WlzObject *obj, double delta, WlzErrorNum *dstErr)
WlzObject * WlzGreyScale (WlzObject *obj, double scale, WlzErrorNum *dstErr)
WlzObject * WlzRGBAGreyScale (WlzObject *obj, double *scale, WlzErrorNum *dstErr)
double WlzGreyMeanDifference (WlzObject *obj1, WlzObject *obj2, double samplePercent, WlzErrorNum *dstErr)
WlzErrorNum DumbRegMatch (WlzDVertex2 *shift, double *matchVal, WlzObject *obj1, WlzObject *obj2, WlzIVertex2 maxShift)
WlzPatchTree * WlzPatchTreeUnalignedChild (WlzPatchTree *patchTree, int depth, WlzDVertex2 *shift)
int WlzPatchMaxDepth (WlzPatchTree *patchTree)
WlzErrorNum WlzRegisterPatchTreeBF (WlzPatchTree *patchTree)
WlzErrorNum WlzRegisterPatchTreeDF (WlzPatchTree *patchTree)
WlzObject * WlzPatchTreeToObject (WlzPatchTree *patchTree, int alignGreysFlg)
int WlzPatchHitBuffers (WlzPatchTree *patchTree)
WlzErrorNum WlzPrintPatchTree (WlzPatchTree *patchTree, FILE *fp, int depth)
WlzErrorNum WlzPatchFacts (WlzPatchTree *patchTree, FILE *fp, char **dstStr, int verbose)
int main (int argc, char **argv)
Detailed Description
Registers patch objects and outputs a single object.
Author
Richard Baldock
Date
February 1998
Version
Id
f0cf0ee0d69ef8c72ddc9f8ee95777d2d64d787c
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Binary
WlzPatchObjRegister
Typedef Documentation
typedef struct _patchTree WlzPatchTree
Function Documentation
int WlzIsAdjacentPatch (WlzObject * obj1, WlzObject * obj2)
References _WlzObject::domain, _WlzDomain::i, _WlzIntervalDomain::kol1, _WlzIntervalDomain::lastkl, _WlzIntervalDomain::lastln, and _WlzIntervalDomain::line1.
Referenced by WlzGetPatchTree(), and WlzGetPatchTreeToDepth().
int sortPatch (const void * p1, const void * p2)
References _patchTree::cost.
Referenced by WlzGetPatchTreeToDepth().
WlzPatchTree* WlzMakePatchTree (WlzObject * obj, int depth, double cost)
References AlcCalloc(), _patchTree::cost, _patchTree::depth, _patchTree::obj, and WlzAssignObject().
Referenced by main(), and WlzGetPatchTreeToDepth().
WlzErrorNum WlzGetPatchTreeToDepth (WlzObject ** objs, int nobjs, WlzPatchTree * patchTree, int depth)
References _patchTree::children, _patchTree::depth, _patchTree::index, _patchTree::nchildren, _patchTree::obj, sortPatch(), WLZ_ERR_NONE, WLZ_GREY_RGBA, WlzFreeObj(), WlzGreyStats(), WlzGreyTypeFromObj(), WlzIsAdjacentPatch(), WlzMakePatchTree(), and WlzRGBAToModulus().
Referenced by main().
WlzPatchTree* WlzGetPatchTree (WlzObject * obj, WlzObject ** objs, int nobjs)
References AlcCalloc(), _patchTree::children, _patchTree::nchildren, _patchTree::obj, _patchTree::offsetsCalculatedFlag, WlzAssignObject(), WlzFreeObj(), and WlzIsAdjacentPatch().
Referenced by main().
WlzErrorNum WlzFreePatchTree (WlzPatchTree * patchTree)
References AlcFree(), _patchTree::children, _patchTree::nchildren, _patchTree::obj, WLZ_ERR_NONE, and WlzFreeObj().
Referenced by main().
double WlzMass (WlzObject * obj, WlzErrorNum * dstErr)
References _WlzIntervalWSpace::colrmn, _WlzDomain::core, _WlzGreyP::dbp, _WlzObject::domain, _WlzGreyP::flp, _WlzGreyP::inp, _WlzGreyWSpace::pixeltype, _WlzGreyP::shp, _WlzObject::type, _WlzGreyWSpace::u_grintptr, _WlzGreyP::ubp, WLZ_2D_DOMAINOBJ, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_EOO, WLZ_ERR_GREY_TYPE, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WlzInitGreyScan(), and WlzNextGreyInterval().
WlzObject* WlzGreyShift (WlzObject * obj, double delta, WlzErrorNum * dstErr)
References _WlzIntervalWSpace::colrmn, _WlzValues::core, _WlzDomain::core, _WlzGreyP::dbp, _WlzObject::domain, _WlzGreyP::flp, _WlzGreyP::inp, _WlzGreyWSpace::pixeltype, _WlzGreyP::shp, _WlzObject::type, _WlzCoreDomain::type, _WlzGreyWSpace::u_grintptr, _WlzGreyP::ubp, _WlzObject::values, WLZ_2D_DOMAINOBJ, WLZ_3D_DOMAINOBJ, WLZ_CLAMP, WLZ_EMPTY_DOMAIN, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_EOO, WLZ_ERR_GREY_TYPE, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_VALUES_NULL, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WLZ_TRANS_OBJ, WlzCopyObject(), WlzFreeObj(), WlzInitGreyScan(), WlzMakeEmpty(), and WlzNextGreyInterval().
WlzObject* WlzGreyScale (WlzObject * obj, double scale, WlzErrorNum * dstErr)
References _WlzIntervalWSpace::colrmn, _WlzValues::core, _WlzDomain::core, _WlzGreyP::dbp, _WlzObject::domain, _WlzGreyP::flp, _WlzGreyP::inp, _WlzGreyWSpace::pixeltype, _WlzGreyP::shp, _WlzObject::type, _WlzCoreDomain::type, _WlzGreyWSpace::u_grintptr, _WlzGreyP::ubp, _WlzObject::values, WLZ_2D_DOMAINOBJ, WLZ_3D_DOMAINOBJ, WLZ_CLAMP, WLZ_EMPTY_DOMAIN, WLZ_EMPTY_OBJ, WLZ_ERR_DOMAIN_NULL, WLZ_ERR_EOO, WLZ_ERR_GREY_TYPE, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_VALUES_NULL, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WLZ_TRANS_OBJ, WlzCopyObject(), WlzFreeObj(), WlzInitGreyScan(), WlzMakeEmpty(), and WlzNextGreyInterval().
Referenced by WlzPatchTreeToObject(), and WlzRGBAGreyScale().
WlzObject* WlzRGBAGreyScale (WlzObject * obj, double * scale, WlzErrorNum * dstErr)
References _WlzCompoundArray::o, _WlzObject::type, WLZ_2D_DOMAINOBJ, WLZ_COMPOUND_ARR_1, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_VALUES_TYPE, WLZ_GREY_RGBA, WLZ_RGBA_SPACE_RGB, WlzCompoundToRGBA(), WlzFreeObj(), WlzGreyScale(), WlzGreyTypeFromObj(), WlzMakeCompoundArray(), and WlzRGBAToCompound().
Referenced by WlzPatchTreeToObject().
double WlzGreyMeanDifference (WlzObject * obj1, WlzObject * obj2, double samplePercent, WlzErrorNum * dstErr)
References _WlzIntervalWSpace::colrmn, _WlzGreyP::dbp, _WlzObject::domain, _WlzGreyP::flp, _WlzGreyP::inp, _WlzGreyWSpace::pixeltype, _WlzGreyP::rgbp, _WlzGreyP::shp, _WlzObject::type, _WlzGreyWSpace::u_grintptr, _WlzGreyP::ubp, _WlzObject::values, WLZ_ERR_GREY_TYPE, WLZ_ERR_NONE, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_RGBA, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WLZ_RGBA_BLUE_GET, WLZ_RGBA_GREEN_GET, WLZ_RGBA_RED_GET, WlzAssignValues(), WlzFreeObj(), WlzInitGreyScan(), WlzIntersect2(), WlzMakeMain(), and WlzNextGreyInterval().
Referenced by DumbRegMatch().
WlzErrorNum DumbRegMatch (WlzDVertex2 * shift, double * matchVal, WlzObject * obj1, WlzObject * obj2, WlzIVertex2 maxShift)
References _WlzIVertex2::vtX, _WlzDVertex2::vtX, _WlzIVertex2::vtY, _WlzDVertex2::vtY, WLZ_ERR_NONE, WlzFreeObj(), WlzGreyMeanDifference(), and WlzShiftObject().
Referenced by WlzRegisterPatchTreeBF(), and WlzRegisterPatchTreeDF().
WlzPatchTree* WlzPatchTreeUnalignedChild (WlzPatchTree * patchTree, int depth, WlzDVertex2 * shift)
References _patchTree::children, _patchTree::depth, _patchTree::nchildren, _patchTree::offsetsCalculatedFlag, _WlzDVertex2::vtX, _WlzDVertex2::vtY, _patchTree::xOff, and _patchTree::yOff.
Referenced by WlzRegisterPatchTreeBF().
int WlzPatchMaxDepth (WlzPatchTree * patchTree)
References _patchTree::children, _patchTree::depth, and _patchTree::nchildren.
Referenced by WlzRegisterPatchTreeBF().
WlzErrorNum WlzRegisterPatchTreeBF (WlzPatchTree * patchTree)
References _patchTree::depth, DumbRegMatch(), _patchTree::obj, _patchTree::offsetsCalculatedFlag, _WlzIVertex2::vtX, _WlzDVertex2::vtX, _WlzIVertex2::vtY, _WlzDVertex2::vtY, WLZ_ERR_NONE, WlzAssignObject(), WlzFreeObj(), WlzPatchMaxDepth(), WlzPatchTreeUnalignedChild(), WlzShiftObject(), WlzUnionN(), _patchTree::xOff, and _patchTree::yOff.
Referenced by main().
WlzErrorNum WlzRegisterPatchTreeDF (WlzPatchTree * patchTree)
References _patchTree::children, _WlzObject::domain, DumbRegMatch(), _WlzDomain::i, _patchTree::nchildren, _patchTree::obj, _patchTree::offsetsCalculatedFlag, _WlzIVertex2::vtX, _WlzDVertex2::vtX, _WlzIVertex2::vtY, _WlzDVertex2::vtY, WLZ_ERR_NONE, WlzStandardIntervalDomain(), _patchTree::xOff, and _patchTree::yOff.
Referenced by main().
WlzObject* WlzPatchTreeToObject (WlzPatchTree * patchTree, int alignGreysFlg)
References _patchTree::children, _WlzValues::core, _WlzObject::domain, _patchTree::nchildren, _patchTree::obj, _WlzObject::type, _WlzObject::values, WLZ_GREY_RGBA, WLZ_RGBA_SPACE_RGB, WlzAssignObject(), WlzDiffDomain(), WlzFreeObj(), WlzGreyScale(), WlzGreyStats(), WlzGreyTypeFromObj(), WlzIntersect2(), WlzMakeMain(), WlzRGBAGreyScale(), WlzRGBAGreyStats(), WlzShiftObject(), WlzUnionN(), _patchTree::xOff, and _patchTree::yOff.
Referenced by main().
int WlzPatchHitBuffers (WlzPatchTree * patchTree)
References _patchTree::children, _patchTree::nchildren, _WlzIVertex2::vtX, _WlzIVertex2::vtY, _patchTree::xOff, and _patchTree::yOff.
Referenced by main().
WlzErrorNum WlzPrintPatchTree (WlzPatchTree * patchTree, FILE * fp, int depth)
References AlcMalloc(), _patchTree::children, _patchTree::cost, _patchTree::depth, _patchTree::index, _patchTree::nchildren, and WLZ_ERR_NONE.
Referenced by main().
WlzErrorNum WlzPatchFacts (WlzPatchTree * patchTree, FILE * fp, char ** dstStr, int verbose)
References _patchTree::children, _patchTree::index, _patchTree::nchildren, _patchTree::obj, _patchTree::offsetsCalculatedFlag, WLZ_ERR_NONE, WlzObjectFacts(), _patchTree::xOff, and _patchTree::yOff.
Referenced by main().
int main (int argc, char ** argv)
References AlcFree(), AlcMalloc(), _patchTree::depth, getopt(), _patchTree::index, _WlzGreyV::inv, _WlzCompoundArray::n, _WlzCompoundArray::o, _patchTree::obj, optarg, opterr, optind, _WlzPixelV::type, _WlzObject::type, _WlzPixelV::v, _WlzIVertex2::vtX, _WlzIVertex2::vtY, WLZ_COMPOUND_ARR_1, WLZ_COMPOUND_ARR_2, WLZ_ERR_NONE, WLZ_ERR_READ_EOF, WLZ_ERR_UNSPECIFIED, WLZ_GREY_INT, WLZ_GREY_RGBA, WLZ_THRESH_HIGH, WlzAssignObject(), WlzFreeObj(), WlzFreePatchTree(), WlzGetPatchTree(), WlzGetPatchTreeToDepth(), WlzGreyStats(), WlzGreyTypeFromObj(), WlzMakeEmpty(), WlzMakePatchTree(), WlzPatchFacts(), WlzPatchHitBuffers(), WlzPatchTreeToObject(), WlzPrintPatchTree(), WlzReadObj(), WlzRegisterPatchTreeBF(), WlzRegisterPatchTreeDF(), WlzRGBAToModulus(), WlzThreshold(), and WlzWriteObj().