Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzRGBAThreshold.c File Reference
WlzRGBAThreshold.c File Reference
WlzThreshold
Threshold functions for RGBA objects.
Data Structures
struct _WlzVectorThresholdStruct
Typedefs
typedef struct _WlzVectorThresholdStruct WlzVectorThresholdStruct
Functions
WlzObject * WlzRGBAMultiThreshold (WlzObject *obj, WlzPixelV lowVal, WlzPixelV highVal, WlzUInt combineMode, WlzErrorNum *dstErr)
Apply independent thresholds to each colour channel independently and combine according to the settings encoded in combineMode. Each channel can have one of two modes: WLZ_BO_AND and WLZ_BO_OR. These are encoded into a single mode variable using the RGBA macro, e.g.: WLZ_RGBA_RGBA_SET(combineMode, redMode, greenMode, blueMode, 255);.
int WlzVectorThreshCb (WlzObject *obj, void *clientData, WlzThreshCbStr *cbs)
WlzObject * WlzRGBASliceThreshold (WlzObject *obj, WlzPixelV lowVal, WlzPixelV highVal, WlzErrorNum *dstErr)
WlzObject * WlzRGBABoxThreshold (WlzObject *obj, WlzPixelV lowVal, WlzPixelV highVal, WlzErrorNum *dstErr)
WlzObject * WlzRGBAEllipsoidThreshold (WlzObject *obj, WlzPixelV lowVal, WlzPixelV highVal, double eccentricity, WlzErrorNum *dstErr)
Detailed Description
Threshold functions for RGBA objects.
Author
Richard Baldock
Date
July 2003
Version
Id
a66c88e72acad40e0fd950a3008d03ed702c0ece
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Typedef Documentation
typedef struct _WlzVectorThresholdStruct WlzVectorThresholdStruct
Function Documentation
int WlzVectorThreshCb (WlzObject * obj, void * clientData, WlzThreshCbStr * cbs)
References _WlzGreyP::dbp, _WlzVectorThresholdStruct::direction, _WlzVectorThresholdStruct::dist, _WlzGreyP::flp, _WlzGreyP::inp, _WlzVectorThresholdStruct::origin, _WlzPixelP::p, _WlzThreshCbStr::pix, _WlzGreyP::rgbp, _WlzGreyP::shp, _WlzVectorThresholdStruct::type, _WlzPixelP::type, _WlzGreyP::ubp, WLZ_GREY_DOUBLE, WLZ_GREY_FLOAT, WLZ_GREY_INT, WLZ_GREY_RGBA, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, WLZ_RGBA_BLUE_GET, WLZ_RGBA_GREEN_GET, WLZ_RGBA_RED_GET, WLZ_RGBA_THRESH_SLICE, and WLZ_RGBA_THRESH_SPHERE.
Referenced by WlzRGBAEllipsoidThreshold(), and WlzRGBASliceThreshold().
WlzObject* WlzRGBASliceThreshold (WlzObject * obj, WlzPixelV lowVal, WlzPixelV highVal, WlzErrorNum * dstErr)
References _WlzVectorThresholdStruct::direction, _WlzVectorThresholdStruct::dist, _WlzVectorThresholdStruct::origin, _WlzVectorThresholdStruct::type, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_RGBA_CHANNEL_BLUE, WLZ_RGBA_CHANNEL_GREEN, WLZ_RGBA_CHANNEL_RED, WLZ_RGBA_THRESH_SLICE, WlzCbThreshold(), WlzRGBAPixelValue(), and WlzVectorThreshCb().
WlzObject* WlzRGBABoxThreshold (WlzObject * obj, WlzPixelV lowVal, WlzPixelV highVal, WlzErrorNum * dstErr)
References _WlzGreyV::rgbv, _WlzPixelV::v, WLZ_BO_AND, WLZ_ERR_NONE, WLZ_RGBA_BLUE_GET, WLZ_RGBA_BLUE_SET, WLZ_RGBA_GREEN_GET, WLZ_RGBA_GREEN_SET, WLZ_RGBA_RED_GET, WLZ_RGBA_RED_SET, WLZ_RGBA_RGBA_SET, and WlzRGBAMultiThreshold().
Referenced by WlzSplitMontageObj().
WlzObject* WlzRGBAEllipsoidThreshold (WlzObject * obj, WlzPixelV lowVal, WlzPixelV highVal, double eccentricity, WlzErrorNum * dstErr)
References _WlzVectorThresholdStruct::direction, _WlzVectorThresholdStruct::dist, _WlzVectorThresholdStruct::eccen, _WlzVectorThresholdStruct::origin, _WlzVectorThresholdStruct::type, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_RGBA_CHANNEL_BLUE, WLZ_RGBA_CHANNEL_GREEN, WLZ_RGBA_CHANNEL_RED, WLZ_RGBA_THRESH_SPHERE, WlzCbThreshold(), WlzRGBAPixelValue(), and WlzVectorThreshCb().