Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzRGBAScalarBinaryOp.c File Reference
WlzRGBAScalarBinaryOp.c File Reference
WlzArithmetic
Apply a scalar binary operation to an RGBA image.
Functions
WlzObject * WlzRGBAScalarBinaryOp (WlzObject *o1, WlzPixelV pval, WlzBinaryOperatorType op, WlzErrorNum *dstErr)
Performs scalar operation on objects with RGBA values.
Detailed Description
Apply a scalar binary operation to an RGBA image.
Author
Richard Baldock
Date
January 2008
Version
Id
a67bb2a11c2d86ea655086b2624315e1af659431
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzRGBAScalarBinaryOp()
WlzObject* WlzRGBAScalarBinaryOp (WlzObject * o1, WlzPixelV pval, WlzBinaryOperatorType op, WlzErrorNum * dstErr)
Performs scalar operation on objects with RGBA values.
Returns
Woolz error code.
Parameters
o1 Input object.
pval Operand value.
op Opertor to be applied.
dstErr Destination error pointer, may be NULL.
References _WlzCompoundArray::o, WLZ_ERR_NONE, WLZ_ERR_OBJECT_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_GREY_RGBA, WLZ_RGBA_SPACE_RGB, WlzCompoundToRGBA(), WlzFreeObj(), WlzGreyTypeFromObj(), WlzRGBAToCompound(), and WlzScalarBinaryOp().