Woolz Image Processing: /export/data0/bill/MouseAtlas/Build/src/Woolz/libWlz/WlzStringTypes.c File Reference
WlzStringTypes.c File Reference
WlzStrings
Functions for converting between Woolz data types and string representations (names) of the types.
Functions
const char * WlzStringFromObjType (WlzObject *obj, WlzErrorNum *dstErr)
Finds a string for the given object's type.
const char * WlzStringFromObjTypeValue (WlzObjectType objType, WlzErrorNum *dstErr)
Finds a string for the given object type.
WlzObjectType WlzStringToObjType (const char *oTypeStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given object type string.
const char * WlzStringFromObjDomainType (WlzObject *obj, WlzErrorNum *dstErr)
Finds a string for the given object's domain type.
WlzObjectType WlzStringToObjDomainType (const char *oDomTypeStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given object domain type string.
const char * WlzStringFromObjValuesType (WlzObject *obj, WlzErrorNum *dstErr)
Finds a string for the given object's values type.
WlzObjectType WlzStringToObjValuesType (const char *oValTypeStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given object values type string.
const char * WlzStringFromScalarFeatureType (WlzScalarFeatureType fType, WlzErrorNum *dstErr)
Finds a string for the given scalar feature type.
WlzScalarFeatureType WlzStringToScalarFeatureType (const char *fTypeStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given scalar feature type.
const char * WlzStringFromPropertyType (WlzProperty prop, WlzErrorNum *dstErr)
Finds a string for the given property's type.
WlzObjectType WlzStringToPropertyType (const char *pStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given property type string.
const char * WlzStringFromEMAPPropertyType (WlzEMAPProperty *eProp, WlzErrorNum *dstErr)
Finds a string for the given EMAP property's type.
WlzEMAPPropertyType WlzStringToEMAPPropertyType (const char *pStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given EMAP property type string.
const char * WlzStringFromTransformType (WlzTransformType tType, WlzErrorNum *dstErr)
Finds a string for the given transform type.
WlzTransformType WlzStringToTransformType (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given transform type string.
const char * WlzStringFromMeshGenMethod (WlzMeshGenMethod mtd, WlzErrorNum *dstErr)
Finds a string for the given mesh generation method.
WlzMeshGenMethod WlzStringToMeshGenMethod (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given mesh generation method.
WlzFnType WlzStringToFnType (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given function type.
const char * WlzStringFromFnType (WlzFnType fn, WlzErrorNum *dstErr)
Finds a string for the given function type.
const char * WlzStringFromGMModelType (WlzGMModelType mType, WlzErrorNum *dstErr)
Finds a string for the given transform type.
WlzGMModelType WlzStringToGMModelType (const char *tStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given GM model type string.
const char * WlzStringFromGreyType (WlzGreyType gType, WlzErrorNum *dstErr)
Finds a string for the given grey type.
WlzGreyType WlzStringToGreyType (const char *gStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given grey type string.
const char * WlzStringFromVertexType (WlzVertexType vType, WlzErrorNum *dstErr)
Finds a string for the given vertex type.
WlzVertexType WlzStringToVertexType (const char *vStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given vertex type string.
const char * WlzStringFromInterpolationType (WlzInterpolationType iType, WlzErrorNum *dstErr)
Finds a string for the given interpolation type.
WlzInterpolationType WlzStringToInterpolationType (const char *iStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given interpolation type string.
const char * WlzStringFromValueAttachType (WlzValueAttach at, WlzErrorNum *dstErr)
Finds a string for the given values attachment type.
WlzValueAttach WlzStringToValuesAttachType (const char *aStr, WlzErrorNum *dstErr)
Finds an enumerated type for the given values attachment type string.
const char * WlzStringFromThreeDViewMode (WlzThreeDViewMode vMode, WlzErrorNum *dstErr)
Finds a string for the given 3D view mode.
WlzThreeDViewMode WlzStringToThreeDViewMode (const char *vStr, WlzErrorNum *dstErr)
Gets a 3D view mode from a string.
const char * WlzStringFromRCC (WlzRCCClass cls, WlzErrorNum *dstErr)
Finds a string for the given region connected calculus class.
WlzRCCClass WlzStringToRCCClass (const char *cStr, WlzErrorNum *dstErr)
Gets a RCC class type from a string.
const char * WlzStringFromMarkerType (WlzMarkerType mType, WlzErrorNum *dstErr)
Finds a string for the given values attachment type.
WlzMarkerType WlzStringToMarkerType (const char *markerStr, WlzErrorNum *dstErr)
Gets a marker type from a string.
const char * WlzStringFromErrorNum (WlzErrorNum wlzErr, const char **dstMsgStr)
Finds a string for the given error.
WlzErrorNum WlzStringToErrorNum (const char *errStr)
Finds an error number for the given error number string.
Detailed Description
Functions for converting between Woolz data types and string representations (names) of the types.
Author
Bill Hill
Date
March 1999
Version
Id
8a4ce0f91d25996626bd35da8613cbe4302f8cbc
Address: MRC Human Genetics Unit, MRC Institute of Genetics and Molecular Medicine, University of Edinburgh, Western General Hospital, Edinburgh, EH4 2XU, UK.
Copyright (C), [2012], The University Court of the University of Edinburgh, Old College, Edinburgh, UK.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
WlzScalarFeatureType WlzStringToScalarFeatureType (const char * fTypeStr, WlzErrorNum * dstErr)
Finds an enumerated type for the given scalar feature type.
Returns
Feature type.
Parameters
fTypeStr Given scalar feature type string.
dstErr Destination error pointer, may be null.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_TYPE, WLZ_SCALARFEATURE_GRADIENT, WLZ_SCALARFEATURE_VALUE, and WlzStringMatchValue().
WlzThreeDViewMode WlzStringToThreeDViewMode (const char * vStr, WlzErrorNum * dstErr)
Gets a 3D view mode from a string.
Returns
Marker type.
Parameters
vStr Given 3D view mode string.
dstErr Destination error pointer, may be NULL.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_TYPE, WLZ_FIXED_LINE_MODE, WLZ_STATUE_MODE, WLZ_UP_IS_UP_MODE, WLZ_ZERO_ZETA_MODE, WLZ_ZETA_MODE, and WlzStringMatchValue().
WlzRCCClass WlzStringToRCCClass (const char * cStr, WlzErrorNum * dstErr)
Gets a RCC class type from a string.
Returns
Region connected calculus class.
Parameters
cStr Given marker string.
dstErr Destination error pointer, may be NULL.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_TYPE, WLZ_RCC_DC, WLZ_RCC_EC, WLZ_RCC_EMPTY, WLZ_RCC_ENC, WLZ_RCC_ENCI, WLZ_RCC_EQ, WLZ_RCC_NTPP, WLZ_RCC_NTPPI, WLZ_RCC_NTSUR, WLZ_RCC_NTSURI, WLZ_RCC_OST, WLZ_RCC_PO, WLZ_RCC_TPP, WLZ_RCC_TPPI, WLZ_RCC_TSUR, WLZ_RCC_TSURI, and WlzStringMatchValue().
WlzMarkerType WlzStringToMarkerType (const char * markerStr, WlzErrorNum * dstErr)
Gets a marker type from a string.
Returns
Marker type.
Parameters
markerStr Given marker string.
dstErr Destination error pointer, may be NULL.
References WLZ_ERR_NONE, WLZ_ERR_PARAM_TYPE, WLZ_MARKER_NONE, WLZ_MARKER_POINT, WLZ_MARKER_SPHERE, and WlzStringMatchValue().